### ISSUE TITLE
Mousewheel quick keybinding

### ISSUE THREAD

**Issue by MannySJH** [Karl-HeinzSchneider/WoW-DragonflightUI#104]
Can't quickly keybind mousewheel + mods, also can't hide stancebar

**Comment by Karl-HeinzSchneider** [comment]
Mousewheel isn't in the original retail QuickKeybind, but I added it for the next version: 7f0d6fca95934c570412a3b381dd6c4b0fef720a

I'm already working on some updates for Stance(and Pet)Bar, should be no problem to add an option to hide it.
