### ISSUE TITLE
Action bar stutter on glowing icons. 

### ISSUE THREAD

**Issue by MannySJH** [Karl-HeinzSchneider/WoW-DragonflightUI#110]
Getting a heavy stutter when I activate trap launcher on my hunter with the action bar module enabled. Gone back to dominos for now for the bars. I think it has to do with how the glowing trap icons are triggered since the stutter also happens when you cancelaura the trap launcher and the icons deluminate.

**Comment by MannySJH** [comment]
https://streamable.com/w5p3vq
https://streamable.com/prut4r
Links to both

**Comment by Karl-HeinzSchneider** [comment]
Should be fixed with 3ab42a5899c897d28a2b4032af612baf6bc398f0
I'll try to push a manual update to curseforge. (Working on a very big update going live in a few days, and the main branch is already too far along for a small fix update with the automatic upload action 😑 my bad)
