### ISSUE TITLE
Problem with greyed out Modules in Setup and green bar fixed on screen

### ISSUE THREAD

**Issue by wdchppr** [Karl-HeinzSchneider/WoW-DragonflightUI#113]
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/150334369/dc598001-1fbd-4a6d-9665-5e259d50c7a6)

Hello Heinz

I have seen that this problem have been reported with version 10.1 already. I got the same problem with the current version. Any idea?

**Comment by wdchppr** [comment]
Okay... Problem seems to only occur when loaded together with console port.

**Comment by Karl-HeinzSchneider** [comment]
Yeah, Console Port is heavily changing the actionbar, so both are not compatible in that sense. But you could deactivate the DragonflightUI Actionbar module, and everything should work.
