### ISSUE TITLE
Broken on SOD PTR

### ISSUE THREAD

**Issue by sandervspl** [Karl-HeinzSchneider/WoW-DragonflightUI#114]
I have disabled all other addons. This only happened a certain update (I want to say 10.2 but I'm not 100% sure). I already tried reinstalling and deleting saved variables etc.

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/4492636/cd59a27e-4bb8-4e57-adcc-2da40a9acbf5)
Misaligned action bars, module options are not selectable

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/4492636/ab40d189-29c3-4da4-9398-2e9dc10966ab)
XP bar in the middle of my screen that I can't move

Also chat says v0.10.2 but I'm on v0.10.3 according to curseforge

**Comment by Karl-HeinzSchneider** [comment]
Hey,
I'll install the PTR and take a look.
(Version in the chat might be wrong because I manually uploaded a small bug fix and maybe didnt change the version in the .toc file)

**Comment by Karl-HeinzSchneider** [comment]
Modules/Actionbar.lua

line 2851
```
Module.ChangeMicroMenuButton(SocialsMicroButton, 'GuildCommunities')
```

comment that out, so

line 2851
```
--Module.ChangeMicroMenuButton(SocialsMicroButton, 'GuildCommunities')
```

Than it seems to work (They changed to the new guild frame).
But there are still errors left, but they dont seem to make much sense, needs more investigation.

**Comment by Karl-HeinzSchneider** [comment]
I fixed it!
Everything should work fine, but if you want the errors gone now:
delete 'Blizzard_Collections' from  '## OptionalDeps:' in DragonflightUI.toc

**Comment by Karl-HeinzSchneider** [comment]
v0.11 (with those fixes ) on its way to Curseforge.
