### ISSUE TITLE
LUA error on wotlk v0.10.2

### ISSUE THREAD

**Issue by Earthoofer** [Karl-HeinzSchneider/WoW-DragonflightUI#115]
I'm using the v0.10.2 version which applies to wotlk as the Chinese servers have reopened from this expansion. Im not sure which part of the issues cause that many of the options is greyed out.

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/174394320/e0767e76-1a37-447c-bf52-3bb2d1a73945)

Message: ...nterface/AddOns/DragonflightUI/Modules/Actionbar.lua:1527: attempt to call method 'UpdateAction' (a nil value)
Time: Tue Jul  2 08:45:35 2024
Count: 1
Stack: ...nterface/AddOns/DragonflightUI/Modules/Actionbar.lua:1527: attempt to call method 'UpdateAction' (a nil value)
[string "@Interface/AddOns/DragonflightUI/Modules/Actionbar.lua"]:1527: in function `createExtra'
[string "@Interface/AddOns/DragonflightUI/Modules/Actionbar.lua"]:1541: in function `SetupActionbarFrames'
[string "@Interface/AddOns/DragonflightUI/Modules/Actionbar.lua"]:1452: in function <...nterface/AddOns/DragonflightUI/Modules/Actionbar.lua:1439>
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function <...ce/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:516>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DragonflightUI/Modules/Config.lua"]:122: in function `ApplySettings'
[string "@Interface/AddOns/DragonflightUI/Mixin/Modules.mixin.lua"]:72: in function `SetOption'
[string "@Interface/AddOns/DragonflightUI/Modules/Config.lua"]:40: in function <Interface/AddOns/DragonflightUI/Modules/Config.lua:39>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua"]:64: in function <...e/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua:63>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:178: in function <Interface/SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua"]:196: in function <...e/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua:194>

Locals: n = 6
btns = <table> {
 1 = DragonflightUIMultiactionBar6Button1 {
 }
}
(for index) = 1
(for limit) = 12
(for step) = 1
i = 1
btn = DragonflightUIMultiactionBar6Button1 {
 0 = <userdata>
 HotKey = DragonflightUIMultiactionBar6Button1HotKey {
 }
 action = 145
 NewActionTexture = Texture {
 }
 Border = DragonflightUIMultiactionBar6Button1Border {
 }
 Flash = DragonflightUIMultiactionBar6Button1Flash {
 }
 flashtime = 0
 Name = DragonflightUIMultiactionBar6Button1Name {
 }
 icon = DragonflightUIMultiactionBar6Button1Icon {
 }
 command = "CLICK DragonflightUIMultiactionBar6Button1:LeftButton"
 AutoCastable = Texture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 feedback_action = 145
 commandHuman = "Action Bar 6 Button 1"
 SpellHighlightTexture = Texture {
 }
 flashing = 0
 NormalTexture = DragonflightUIMultiactionBar6Button1NormalTexture {
 }
 FlyoutBorderShadow = DragonflightUIMultiactionBar6Button1FlyoutBorderShadow {
 }
 FlyoutBorder = DragonflightUIMultiactionBar6Button1FlyoutBorder {
 }
 Count = DragonflightUIMultiactionBar6Button1Count {
 }
 AutoCastShine = DragonflightUIMultiactionBar6Button1Shine {
 }
 FlyoutArrow = DragonflightUIMultiactionBar6Button1FlyoutArrow {
 }
 cooldown = DragonflightUIMultiactionBar6Button1Cooldown {
 }
 zoneAbilityDisabled = false
}
(*temporary) = nil
(*temporary) = DragonflightUIMultiactionBar6Button1 {
 0 = <userdata>
 HotKey = DragonflightUIMultiactionBar6Button1HotKey {
 }
 action = 145
 NewActionTexture = Texture {
 }
 Border = DragonflightUIMultiactionBar6Button1Border {
 }
 Flash = DragonflightUIMultiactionBar6Button1Flash {
 }
 flashtime = 0
 Name = DragonflightUIMultiactionBar6Button1Name {
 }
 icon = DragonflightUIMultiactionBar6Button1Icon {
 }
 command = "CLICK DragonflightUIMultiactionBar6Button1:LeftButton"
 AutoCastable = Texture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 feedback_action = 145
 commandHuman = "Action Bar 6 Button 1"
 SpellHighlightTexture = Texture {
 }
 flashing = 0
 NormalTexture = DragonflightUIMultiactionBar6Button1NormalTexture {
 }
 FlyoutBorderShadow = DragonflightUIMultiac

### Part2
Message: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:155: attempt to index local 'state' (a nil value)
Time: Tue Jul  2 08:48:33 2024
Count: 4
Stack: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:155: attempt to index local 'state' (a nil value)
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:155: in function `Update'
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:19: in function <...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:18>

Locals: self = DragonflightUIXPBar {
 0 = <userdata>
 TextPercent = Text {
 }
 Border = Border {
 }
 SetupTooltip = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:94
 CreateBar = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:22
 Text = Text {
 }
 Update = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:140
 OnEvent = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:18
 UpdateText = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:180
 RestedBarMark = Frame {
 }
 SetState = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:135
 RestedBar = StatusBar {
 }
 OnLoad = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:5
 Background = Background {
 }
 Collapse = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:236
 Bar = StatusBar {
 }
}
state = nil
showXP = true
(*temporary) = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:180
(*temporary) = DragonflightUIXPBar {
 0 = <userdata>
 TextPercent = Text {
 }
 Border = Border {
 }
 SetupTooltip = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:94
 CreateBar = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:22
 Text = Text {
 }
 Update = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:140
 OnEvent = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:18
 UpdateText = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:180
 RestedBarMark = Frame {
 }
 SetState = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:135
 RestedBar = StatusBar {
 }
 OnLoad = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:5
 Background = Background {
 }
 Collapse = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:236
 Bar = StatusBar {
 }
}
(*temporary) = 466
(*temporary) = 20
(*temporary) = 14
(*temporary) = 20
(*temporary) = -1
(*temporary) = 2
(*temporary) = "attempt to index local 'state' (a nil value)"
DF = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> defined @Interface/AddOns/Questie/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 GetClassColor = <function> defined @Interface/AddOns/DragonflightUI/Core.lua:51
 EnableModule = <function> defined @Interface/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 ReloadCommand = <function> defined @Interface/AddOns/DragonflightUI/Config.lua:97
 SecureHook = <function> defined @Interface/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 ConfigModule = <table> {
 }
 OptionTableProfiles = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface/AddOns/Questie/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 RawHookScript = <function> defined @Interface/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:394
 optFrames

**Comment by Karl-HeinzSchneider** [comment]
in Modules/Actionbar.lua, line 1528:

 ```
btn:UpdateAction()
```

just comment it out like so:
```
-- btn:UpdateAction()
```


Chinese Wotlk is hard to support, because I cant play on the server myself.

**Comment by Earthoofer** [comment]
> in Modules/Actionbar.lua, line 1528:
> 
> ```
> btn:UpdateAction()
> ```
> 
> just comment it out like so:
> 
> ```
> -- btn:UpdateAction()
> ```
> 
> Chinese Wotlk is hard to support, because I cant play on the server myself.

The solution functions flawlessly. Yeah I realize that ongoing work may not be feasible, I appreciate your assistance!
