### ISSUE TITLE
Micromenu tabs issue

### ISSUE THREAD

**Issue by HumptyD** [Karl-HeinzSchneider/WoW-DragonflightUI#117]
Hi! Thank you for the addon!
There are two tabs with the same image in the micromenu (Atlas and PvP tabs)
Client - Client WoW Cata
<img width="377" alt="Screenshot 2024-07-03 at 21 48 53" src="https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/42269621/5bfb94d7-ee55-416f-a9b3-af998988808e">

**Comment by Karl-HeinzSchneider** [comment]
Hey,
this is kind of intended, but more so because retail doesn't have a fitting Icon for the PVP button:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/6ab6a7a0-d0ef-4684-94c8-acd91e27e84d)
Tried to find something else in this style, but so far nothing.

**Comment by Karl-HeinzSchneider** [comment]
Same with the World Map Button on Era, but some guy on Curseforge made one for me 😂

**Comment by HumptyD** [comment]
Ok, thank you! Good luck!

**Comment by Karl-HeinzSchneider** [comment]
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/2b7cff20-d9ae-4aab-b8e3-8ceb45fd3c11)

**Comment by HumptyD** [comment]
Perfect!

**Comment by Karl-HeinzSchneider** [comment]
Pressed button state is not perfect yet, but good for now: 9a48f499bc0171e5822f90be3a0d9b932b9c8423
