### ISSUE TITLE
Frame strata on professions superceded by unit frames

### ISSUE THREAD

**Issue by MannySJH** [Karl-HeinzSchneider/WoW-DragonflightUI#118]
![Capture](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/168474168/8d2f96ef-c38b-47a5-80d6-64509ab8eb0c)
Unit frames should be behind professions, really nice work though on the UI

![Capture](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/168474168/fe7e2635-7d45-4713-9ccb-1a1cc4de0cbb)
Also this bug happened, not sure how I did it but doesn't seem to revert back with reload or disabling renabling addon. Think it's related to the expand window option

**Comment by Karl-HeinzSchneider** [comment]
FrameStrata is fixed for the next version: f7a0c2728497e9f8b280c856666c2bcd5c037686

I'll try to reproduce the other issue.

**Comment by MannySJH** [comment]
Could be related to jewelcrafting, looks like it was fine in the engineering window, when I opened the JC window it happened.

**Comment by Karl-HeinzSchneider** [comment]
I couldn't reproduce the reagent icons getting stuck on the left side, but you're not the only one reporting that. 

For me, on the first open after reload, they were completely missing, and it fixed itself after changing the recipe. I fixed this with changeing something about the anchoring (5a0e6753f37d79353adc9a9f2bb623c2ec1b255e) (the UI didnt update the layering correctly, which seems like a Blizzard bug). Maybe this was the same bug, will push update later.

**Comment by AlessandroPass** [comment]
Heyo! I love this addon and I ran into the same problem described here.

I took the liberty of seeing if it was a compatibility failure with another addon and it is possible that that is the problem, currently I managed to recreate the bug, the problem in my case is the Auctionator v10.2.48

I made a video in case it helps you recreate the problem. 

Thanks for the addon!

https://youtu.be/f1haDXa4fvE

**Comment by Karl-HeinzSchneider** [comment]
> Heyo! I love this addon and I ran into the same problem described here.
> 
> I took the liberty of seeing if it was a compatibility failure with another addon and it is possible that that is the problem, currently I managed to recreate the bug, the problem in my case is the Auctionator v10.2.48
> 
> I made a video in case it helps you recreate the problem.
> 
> Thanks for the addon!
> 
> https://youtu.be/f1haDXa4fvE

Auctionator is reanchoring the reagent icons because of the 'Show crafting cost in crafting view' option.
I think I fixed it with 4b6693070d01e7115aa5e84751fa5897484a5439
I'm waiting 1-2 days if other fixes are needed before I push it to curseforge.
