### ISSUE TITLE
Lua error when opening achievements with micromenu hidden

### ISSUE THREAD

**Issue by MannySJH** [Karl-HeinzSchneider/WoW-DragonflightUI#119]
Message: ...izzard_AchievementUI/Cata/Blizzard_AchievementUI.lua:542: attempt to call global 'AchievementMicroButton_Update' (a nil value)
Time: Sat Jul  6 23:28:21 2024
Count: 1
Stack: ...izzard_AchievementUI/Cata/Blizzard_AchievementUI.lua:542: attempt to call global 'AchievementMicroButton_Update' (a nil value)
[string "@Interface/AddOns/Blizzard_AchievementUI/Cata/Blizzard_AchievementUI.lua"]:542: in function <...izzard_AchievementUI/Cata/Blizzard_AchievementUI.lua:490>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Cata/UIParent.lua"]:247: in function `UIParentLoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Cata/UIParent.lua"]:330: in function `AchievementFrame_LoadUI'
[string "@Interface/AddOns/Blizzard_UIParent/Cata/UIParent.lua"]:437: in function `ToggleAchievementFrame'
[string "TOGGLEACHIEVEMENT"]:1: in function <[string "TOGGLEACHIEVEMENT"]:1>

Locals: self = AchievementFrameAchievements {
 0 = <userdata>
 forceOnShow = <function> defined @Interface/AddOns/Blizzard_AchievementUI/Cata/Blizzard_AchievementUI.lua:442
 buttons = <table> {
 }
 label = Frame {
 }
}
event = "ADDON_LOADED"
(*temporary) = nil
(*temporary) = "attempt to call global 'AchievementMicroButton_Update' (a nil value)"
IN_GUILD_VIEW = nil
guildMemberRequestFrame = nil

![Capture](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/168474168/731a7de7-2b65-49cf-a7ee-7bb3fc1baae9)
Also some buttons pop back in after the error

**Comment by Karl-HeinzSchneider** [comment]
Should be fixed with ef145073d6e85f61049183e916eea69ab029f569
