### ISSUE TITLE
Error logs when opening vendor menu with the addon "Extended Vendor UI"

### ISSUE THREAD

**Issue by sandervspl** [Karl-HeinzSchneider/WoW-DragonflightUI#120]
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/4492636/87b9e9a6-d72e-4a9a-a98f-b75a692a01a5)

**Comment by Karl-HeinzSchneider** [comment]
4e8f67da134349fb4bf03e736fc4bb769beeede0
