### ISSUE TITLE
Buttons are too wide on the social pane in classic era/sod

### ISSUE THREAD

**Issue by sandervspl** [Karl-HeinzSchneider/WoW-DragonflightUI#121]
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/4492636/20ec2bd8-1547-4971-ae87-43bc5cbd903d)

**Comment by Karl-HeinzSchneider** [comment]
This was from the PTR, right? Because on normal SoD the 'Groups' button is not there for me.

Anyway, fixed with f822b230ac2ca3816ec45d3a6b66bb1028563390.

**Comment by sandervspl** [comment]
Hey, no this was on live. Not on PTR
