### ISSUE TITLE
[FR] World map module

### ISSUE THREAD

**Issue by thareh** [Karl-HeinzSchneider/WoW-DragonflightUI#123]
Good day,

A world map module would be swell, have a look at the following for some ideas:
```
WorldMapFrame:SetScale(0.8);
WorldMapFrame.BlackoutFrame.Blackout:SetAlpha(0);
WorldMapFrame.BlackoutFrame:EnableMouse(false);

WorldMapFrame.ScrollContainer.GetCursorPosition = function(f)
   local x,y = MapCanvasScrollControllerMixin.GetCursorPosition(f);
   local s = WorldMapFrame:GetScale();
   return x/s, y/s;
end;
```

Cheers!

**Comment by Karl-HeinzSchneider** [comment]
Hey,
I was also thinking about changing the default map, right now I'm mostly using an addon for that. 
Will take a look at that this week; open to any suggestions about features.

**Comment by Karl-HeinzSchneider** [comment]
Leatrix Maps is too good, I don't think it makes much sense to make a complete map overhaul myself. 
But I would like 2-3 things different, so I might try to code some kind of patch, that hooks into Leatrix Maps and adds functionality, and the dragonflight style.
