### ISSUE TITLE
Quest hand-in modal issue

### ISSUE THREAD

**Issue by Aetherdan** [Karl-HeinzSchneider/WoW-DragonflightUI#125]
The quest hand-in frames / modal thingo (sorry for lack of knowledge on terminology) isn't appearing as intended since the latest update. See attached.

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/29881062/9e3efb85-32e3-4728-9107-1b94462da7fd)

**Comment by Karl-HeinzSchneider** [comment]
Hm, I guess it gets overriden again somewhere. 
Will try to reproduce and fix it later.

**Comment by Karl-HeinzSchneider** [comment]
Fixed with 88fcc047785c2de582573726bf986c9db13aee87.
Will upload to curseforge later

**Comment by Aetherdan** [comment]
@Karl-HeinzSchneider there is one additional panel before you select your reward that has the issue. I have found the fishing/cooking dailies are the best way to reproduce it.

I'm going to guess its the ```QuestFrameProgressPanel```, but I'm not entirely sure how to debug to get the name.
