### ISSUE TITLE
[Bug Report] Disabled actionbars 6-8 are showing

### ISSUE THREAD

**Issue by Gendr** [Karl-HeinzSchneider/WoW-DragonflightUI#129]
**Version:**
DragonflightUI v0.11.5

**Game Version:**
Cataclysm

**Issue:**
Upon login actionbars 6-8 are showing even when disabled.

**Comment by Karl-HeinzSchneider** [comment]
Hey,
I found some blizzard spaghetti code which updates the whole button when show/hide keybind/macro text in some circumstances; should be fixed with f996087d3df8c049ecec2de1420c278eb598f094
