### ISSUE TITLE
LUA Error in Version 0.12.1

### ISSUE THREAD

**Issue by lokisilverblade** [Karl-HeinzSchneider/WoW-DragonflightUI#141]
33x ...faceDragonflightUI/Mixin/ItemColor.mixin.lua:359: attempt to index global 'GuildBankFrame' (a nil value)
[string "@DragonflightUI/Mixin/ItemColor.mixin.lua"]:359: in function `UpdateGuildBankSlots'
[string "@DragonflightUI/Modules/UI.lua"]:102: in function <DragonflightUI/Modules/UI.lua:77>

Locals:
self = <table> {
 AddOverlayToFrame = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:14
 HookInspectFrame = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:112
 HookCharacterFrame = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:81
 UpdateGuildBankSlots = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:351
 OnEvent = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:8
 HookGuildbankBags = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:336
 UpdateAllBags = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:217
 HookBags = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:143
 UpdateMerchantBuyback = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:317
 UpdateBag = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:234
 UpdateMerchant = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:275
 UpdateOverlayQuality = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:57
 UpdateBankSlots = <function> defined @DragonflightUI/Mixin/ItemColor.mixin.lua:257
}
activeTab = 1
itemButton = nil
buttonID = nil
texture = nil
itemCount = nil
locked = nil
isFiltered = nil
quality = nil
(for index) = 1
(for limit) = 7
(for step) = 1
c = 1
(*temporary) = nil
(*temporary) = "Column1"
(*temporary) = "1"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'GuildBankFrame' (a nil value)"

**Comment by Karl-HeinzSchneider** [comment]
Hm, the error doesn't really make sense, so it might be something else. Or its some obscure blizzard bug.
Anyway, I added a simple guard to check if the GuildBankFrame exists: 4ec86f6dbde9ba0feca89801a9177a43be943203

Maybe you could test it out if you can reproduce the error, its a simple 1 line change.

**Comment by lokisilverblade** [comment]
Okay  i want test your fix

**Comment by lokisilverblade** [comment]
Ok it works :)
