### ISSUE TITLE
[BUG] Inspect lua error

### ISSUE THREAD

**Issue by MannySJH** [Karl-HeinzSchneider/WoW-DragonflightUI#152]
Message: Interface/AddOns/DragonflightUI/Mixin/UI.mixin.lua:990: bad argument #1 to 'strupper' (string expected, got nil)
Time: Sun Jul 21 17:59:29 2024
Count: 8
Stack: Interface/AddOns/DragonflightUI/Mixin/UI.mixin.lua:990: bad argument #1 to 'strupper' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `strupper'
[string "@Interface/AddOns/DragonflightUI/Mixin/UI.mixin.lua"]:990: in function <Interface/AddOns/DragonflightUI/Mixin/UI.mixin.lua:982>
[string "@Interface/AddOns/DragonflightUI/Mixin/UI.mixin.lua"]:1009: in function <Interface/AddOns/DragonflightUI/Mixin/UI.mixin.lua:1007>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:606: in function `SetUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:451: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:319: in function <...PanelManager/Classic/UIParentPanelManager_Shared.lua:315>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:1094: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_InspectUI/TBC/Blizzard_InspectUI.lua"]:28: in function <...AddOns/Blizzard_InspectUI/TBC/Blizzard_InspectUI.lua:26>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Karl-HeinzSchneider** [comment]
Hey,
already fixed for the next version with 5f586053c966f3a542348833667943a1eabab224
Will push an update to curseforge later
