### ISSUE TITLE
[BUG] Action bar 4/5 seems mixed up

### ISSUE THREAD

**Issue by psykzz** [Karl-HeinzSchneider/WoW-DragonflightUI#164]
**Describe the bug**
Action bar 4/5 seems mixed up in settings
AlwaysShow seems to be flipped.

**Error Log**
No log, but see attached video 

https://github.com/user-attachments/assets/a43f7568-836d-4725-ac2b-6b14b2485af2

**Versions (please complete the following information):**
 - WoW: SoD
 - Addon [e.g. v0.13.1]

**Additional context**

**Comment by Karl-HeinzSchneider** [comment]
Hey,
I'm working on a rewrite of the active/hidden logic. See #165 

I wrote about that in a comment on curseforge yesterday I think, theres a problem in the blizzard code that the extra actionbars 4/5 are linked together in the options, like you need to activate 4 before you can activate 5.  I already have an idea to override that completely, and use my own logic like in the custom bars 6/7/8.

Greate report btw ❤

**Comment by Karl-HeinzSchneider** [comment]
Should be fixed with 0e07fc26e9c2c68ceea92b290c7507abcb330b1c

**Comment by psykzz** [comment]
Do you publish main as an alpha build? If so i could test this now and validate for you.

**Comment by psykzz** [comment]
Noticed you actually just made a release, which is even better.
So i can confirm 4 is needed for 5, but alwaysShow buttons is working as expected now!

**Comment by Karl-HeinzSchneider** [comment]
> Do you publish main as an alpha build? If so i could test this now and validate for you.

Only sometimes, because the automatic update pipeline is only for releases right now.

But everything should work fine now, because I'm reusing the logic from Actionbar 6/7/8 to show/hide the bar; I just force the blizzard CVars and activate every actionbar, and then handle the visiblity from the config state.
Now every Actionbar should be independent from the others.

**Comment by psykzz** [comment]
Toggling bar 4 does still seem to hide bar 5, but thats acceptable.

**Comment by Karl-HeinzSchneider** [comment]
> Toggling bar 4 does still seem to hide bar 5, but thats acceptable.

You mean toggleing them in the blizzard options, right?
Because I changed the logic so that the blizzard settings get overriden (every actionbar toggle to true), and DragonflightUI handles the Actionbars now, so you would set the visiblity in the DragonflightUI config.

**Comment by Karl-HeinzSchneider** [comment]
But ofc if you change the Blizzard options, they will be hidden again, but after /reload etc they will be set to true again. So you would ignore the blizzard options now.

**Comment by psykzz** [comment]
>You mean toggleing them in the blizzard options, right?

Unfortunately not.


https://github.com/user-attachments/assets/a53de644-7534-4ccb-919b-b059e56b5b32

**Comment by psykzz** [comment]
Unrelated but its also hiding the stancebar after some updates, but it returns on a reload.

**Comment by Karl-HeinzSchneider** [comment]
Ah, you dont have the newest Version v0.13.2.

**Comment by psykzz** [comment]
Apologies i swore i had updated :|

**Comment by psykzz** [comment]
Working great thank you!

**Comment by Karl-HeinzSchneider** [comment]
Haha, classic!
