### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vggfac** [Karl-HeinzSchneider/WoW-DragonflightUI#207]
https://imgur.com/a/cvozJlb

**Comment by vggfac** [comment]
> https://imgur.com/a/cvozJlb

There seems to be some confusion when observing the target

**Comment by Karl-HeinzSchneider** [comment]
This seems to be an Issue with another addon, as the default inspect doesn't show glyphs.
Is this on the new chinese wotlk version?

I think I'll add a simple option to disable changeing the inspect frame, so you could just deactivate that and use your addon for improved inspect. Should be in the next update, in 2-3 days.
