### ISSUE TITLE
[BUG] DragonflightUI bag icons blocking other addons

### ISSUE THREAD

**Issue by mootkins** [Karl-HeinzSchneider/WoW-DragonflightUI#209]
**Describe the bug**
Dragonflight is not working with an addon I am creating. Mainly, it will not let me left or right click bags in order to get to specific options.

Here is what my addon does after left clicking the bag icon without dragonflight: https://i.imgur.com/FHxPCE9.png
Here is what my addon does after left clicking the bag icon with dragonflight active: https://i.imgur.com/xOXw5jE.png

As you can see, the cleanup button still exists from my addon in both, but with dragonflight bags enabled, i cannot left click the top left bag icon to change settings.

**Error Log**
No errors. Just the icons you have for bags are not clickable, so addon loses its functionality.

**Versions (please complete the following information):**
 - WoW: Classic Era
 -  - Addon 0.14.2

**Additional context**
You can contact me on Discord Zeeyaz#2424 if you want to test my addon file for further testing.

**Comment by Karl-HeinzSchneider** [comment]
Hey,
you are using the ContainerFrame**X**PortraitButton, right? 
I had to hide the one on the backpack containerframe, and add a fake texture on top. 

I changed the logic in 47fe095e4acf4f8992b39e3bebcbbc3366ea1ee8, so using the PortraitButton should work for you.
You can check out the alpha, should be on curseforge in a few minutes.

**Comment by Karl-HeinzSchneider** [comment]
Btw I like the retail bag sort, so I was thinking about adding this myself. But other things are on a higher priority right now. 

Hit me up if your addon is on github, maybe I can help out.

**Comment by Karl-HeinzSchneider** [comment]
Any news?
