### ISSUE TITLE
[Feature Request] Skills / Profession window

### ISSUE THREAD

**Issue by psykzz** [Karl-HeinzSchneider/WoW-DragonflightUI#210]
**Is your feature request related to a problem? Please describe.**

My problem is that I dislike having to bind a button for my professions.

**Describe the solution you'd like**

I would love to have an implementation that adds the profession buttons to the skills window, as it is in retail.
![image](https://github.com/user-attachments/assets/3c2a7271-e062-476d-9e50-2d1c8f72362a)

**Additional context**
I would suggest keeping the stat displays as they are but maybe showing them where archeology or other skills may be shown.

**Comment by Karl-HeinzSchneider** [comment]
Hey,
you mean on the Spellbook, like Cata and Retail (extra window, but same style) has it? E.g. 
![image](https://github.com/user-attachments/assets/90bcdce2-c871-47fd-9ae1-4ba3673b39d1)

I would like that, but its a good chunk of work, so don't count on it soon. But I'll add it to the roadmap.

**Comment by psykzz** [comment]
Exactly yes.

**Comment by psykzz** [comment]
@Karl-HeinzSchneider is there anything I could i could do to help?
Do you need help discovering assets, or just time spent putting UI together?

**Comment by Karl-HeinzSchneider** [comment]
> @Karl-HeinzSchneider is there anything I could i could do to help? Do you need help discovering assets, or just time spent putting UI together?

I think if you're not really familiar with the codebase (WoW, and DragonflightUI), it might be difficult. I already have a good idea how to implement it, and already started putting it together:

![image](https://github.com/user-attachments/assets/e09e2a93-6cff-4850-a866-7d0c25d04712)

**Comment by Karl-HeinzSchneider** [comment]
Style is done:
![image](https://github.com/user-attachments/assets/93213a73-c77f-41ed-9f82-1d647b229130)

Now only cleanup, adding update events here and there, and adding the tab logic to the spellbook left. Should be ready this week.

**Comment by Karl-HeinzSchneider** [comment]
I merged it into main. Will be in v0.15.2 in max 1-2 days.
