### ISSUE TITLE
[Feature Request] Hide Calendar Button in Classic (SoD)

### ISSUE THREAD

**Issue by adam-tj** [Karl-HeinzSchneider/WoW-DragonflightUI#230]
**Is your feature request related to a problem? Please describe.**
The a lack of an official calendar in SoD (and Era/HC?)

**Describe the solution you'd like**
An option to hide the button because it doesn't work unless you use "Classic Calendar"

**Comment by Karl-HeinzSchneider** [comment]
Done: 39487676d3e16599aedb53b280e45682e53d1229
On curseforge in ~3-4 days.

**Comment by adam-tj** [comment]
Hey again, I installed the latest version as of the 25th of August from Curseforge and the button doesn't hide when I tick the hide calendar option
