### ISSUE TITLE
[Feature Request] Hiding / Fading everything

### ISSUE THREAD

**Issue by SirFailaLot89** [Karl-HeinzSchneider/WoW-DragonflightUI#231]
### First of all i want to say that i really appreciate your work.

May it be possible to have options to fade out / hide / show when mouseover / show when in combat for parts of the interface? 
I am using an OLED Monitor and trying to avoid burn in. I am currently trying to move over to your UI.

At my current UI everything is hidden, but shown when i mouseover it when out of combat. The actionbars become visible if i enter combat or for classes like druid / rogue if i enter stealth or if i enter combat.

This way, my UI is very clean, because Playerframe, Actionbars, Chat etc. is only shown when mouseover or in combat/stealth or mouseover. It would be nice to have **every part of the UI**  possible to _hide / fade_ and so on. It would also be nice to have the option to _fade them with a slider from 100% to 0%_ and so on.

Thank you for your good work mate!

**Comment by Karl-HeinzSchneider** [comment]
Hey, 
its already planned to add something like that for the actionbars etc, but its a bit of work because those are secure frames, with extra protection from blizzard, so you cant do everything. I already had to use some extra secure code for the profession spellbook on Era, so it might be easier for me now. 
Other frames might follow if its not too much work, but I'll start with the actionbars.

I get the aesthetic choice, but you might overestimate burn in. (I hope you're not playing WoW straight for 20h/day without alt+tab or relog 😋)

**Comment by Karl-HeinzSchneider** [comment]
Current state:
![image](https://github.com/user-attachments/assets/a8ea13e0-6bf6-47a1-a61d-8e8c8cefc628)

Actionbars are ready, and now I'm working on expanding this to other frames.

**Comment by Karl-HeinzSchneider** [comment]
Check out v0.16, and let me know what you think!

**Comment by SirFailaLot89** [comment]
> Oh yes this is amazing! I really appreciate it! This is EXACTLY what i was looking for and i love it!
> 
> What may also a good addition to your UI is the ability to create more profiles for a character, so you can switch between them freely. I do have more than one profile per character especially for hybrids like druid or for Heal/DPS like Priests and so on, if i reskill the talent points i am switching over to another profile created for that spec, because you dont need the same information on screen all the time.
> 
> Thank you for this, i really love it!

Just noticed that you can add profiles within blizzards Addon section, so just ignore the second half.

**Comment by SirFailaLot89** [comment]
Yes i use different profil for each specc! As i am only playing Classic Era, i dont need any automation as the respec is manually and  very very slow.
But for Dual Specc it may be a thing? I dont know do be honest.
Any plans making the xp bar fadeable? :D

**Comment by Karl-HeinzSchneider** [comment]
XP/Rep bar is 2-3min work, should be in the next update.
Chat ist not so easy, but I guess the default fade is ok for now.

**Comment by SirFailaLot89** [comment]
Ok tyvm! I dont know how this coding thing works, maybe you can borrow some code, and have it a bit easier: i am using „smart chat fade“ addon to fade the  (or is it a „red flag“ to borrow code?)

**Comment by Karl-HeinzSchneider** [comment]
Profiles got a refactor/rework:
![image](https://github.com/user-attachments/assets/48404b67-20ce-4148-9dac-7ce784cff207)
(API is not yet done)

**Comment by Karl-HeinzSchneider** [comment]
XP/Repbar state handler: 1f0e208186de49db87549265ba7720776e890aa7 (was <5min with testing included lol)
--
You can *borrow* code from other addons when the licence allows it, like my addons are under MIT licence were you could basicly do everything you like with it, even republish under different name. Directly copying code without licence would be kind of stealing, but also the WoW API is strict sometimes, so you cant really avoid similar code when you use this API. 

Realistically, you could copy 1:1 and nobody would notice it, but would be kind of a dick move. But looking for WoW API functions in other addons code is a grey area most devs would do, but for something like this there would be 100% some code on the internet/reddit/forum in form of a small snippet of code, and most devs would gladly help other devs out.

I'll look into it more for the next update, but if theres already a good addon its not really urgent I guess.

**Comment by SirFailaLot89** [comment]
![twink_DFui](https://github.com/user-attachments/assets/5fdfec74-f872-4b97-af79-db1dd58fe9c1)

So the XP Bar does work very well, just like the other elements.
The only part that is missing (for me personally) is that the Minimap Module is linked to the Buffs, i am using "sexymap addon" here because you can get rid of any buttons and static things at the map, like the "north tag" or "zone tag" and so on. but to use it i have to deactivate the Minimap Modul, this causes the Buffs to be always shown on the top right corner. Are they linked by blizzard?

Danke für deine gute & schnelle Umsetzung! Ich hoff ich mach dir damit nicht allzu viel extra Arbeit!

**Comment by Karl-HeinzSchneider** [comment]
Buffs and Minimap are not linked per se, but the Dragonflight Minimap is bigger, and so you need the changes to the buffs, or it would overlap. And I dont want 100 modules, so those were together.
But I did a refactor and made a seperate Buffs module: ed550e81d6456c70af572681bd2db5cee1725907 (activated as default)

v0.16.2 will be on curseforge later today.

**Comment by SirFailaLot89** [comment]
It does work well with the buffs in the extra module. 
I've noticed in some cases a few buttons reappear / become visible again, for instance if you mount up / off the talent tree button becomes visible again, pressing it or mouseover it will make it disappear again. This also happens with pet bars.

**Comment by Karl-HeinzSchneider** [comment]
Talents button seems to be getting overridden on different occasions, I already had to manually update it one frame after game load because Talents and one other button got shown. I'll take a look later.
