### ISSUE TITLE
[BUG] Hard to see colour fading on spells on the action bar

### ISSUE THREAD

**Issue by adam-tj** [Karl-HeinzSchneider/WoW-DragonflightUI#234]
See hotkey R
Indoors Dragonfly UI (Entangling roots spell not usable), hard to see
![image](https://github.com/user-attachments/assets/fe5df163-2a43-43cd-823f-b634619bc189)
Indoors Default UI (Entangling roots spell not usable), easy to see
![image](https://github.com/user-attachments/assets/82ac4a2a-28a1-4c1b-9da8-e028ea219647)
Outdoors Default UI
![image](https://github.com/user-attachments/assets/3a09de1d-4cdc-4c96-95d3-24be4f62d109)
Outdoors Dragonflight UI
![image](https://github.com/user-attachments/assets/278c2ef9-fd8a-4674-ba73-f1daa2e0364a)

Is the first picture with complete colour desaturating intentional?

**Comment by Karl-HeinzSchneider** [comment]
Kind of intentional, yes. But I'll look into it again, as the default one seems a bit nicer with some color left.

**Comment by Karl-HeinzSchneider** [comment]
The code was
```
 if not isUsable then
        mask:SetVertexColor(0.4, 0.4, 0.4, 1.0)      
        mask:SetDesaturated(true)
        ...
```
I changed the VertexColor back to `mask:SetVertexColor(1.0, 1.0, 1.0, 1.0)`. This should make the button like default when the button is just not usable; out of range is still changed.
