### ISSUE TITLE
[BUG] Regression for Actionbar4

### ISSUE THREAD

**Issue by Niklan** [Karl-HeinzSchneider/WoW-DragonflightUI#242]
**Describe the bug**
Actionbar4 is no longer available in the 0.16.0 release.

Downgraded to 0.15.2 and it is in place.
![image](https://github.com/user-attachments/assets/2d19bf8b-69bf-4485-9a1b-8f66011ae7e8)

All the settings are default.

**Error Log**
There is no any errors.

**Versions (please complete the following information):**
 - WoW: Cata classic
 - Addon v0.16.0

**Additional context**
Simple downgrade is helping. The regression is introduced in [0.16](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/compare/v0.15.2...v0.16).

**Comment by Karl-HeinzSchneider** [comment]
Hey,
If you're using default settings, the right one should be **ActionBar5**.
See `Options > Actionbar5 > Visibility`: deactivate `Always Hide`. These are the new visiblity settings based on macro conditionals, but the default value for `hideAlways` is wrongly set to `true` - small oversight!

Let me know if everything else works fine, or if there are any issues. Or if you have any ideas for improvement!

**Comment by Karl-HeinzSchneider** [comment]
2b8817550b4cba7a0bb3f562350f34b0c3fc3080

**Comment by Niklan** [comment]
![image](https://github.com/user-attachments/assets/04e77592-5330-4452-8512-2d45ebee7387)
Applied changes from https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/commit/2b8817550b4cba7a0bb3f562350f34b0c3fc3080 and it becomes visible on 0.16.

And yes, you are right, it is Actionbar5. I am not sure what Actionbar4 is. Also, it is possible to move it right to the quest log as on retail?

![image](https://github.com/user-attachments/assets/0c0b841d-5891-4899-812a-e1e25f596ab4)

The samll detail, but the main actionbar is missing option for the border:
![image](https://github.com/user-attachments/assets/c90a598a-e754-4561-94d0-b61845376205)
![image](https://github.com/user-attachments/assets/39fb47fd-870d-4a27-8d46-e1245679624c)

It also appears retail has more thick border for buttons.

P.s. It would be nice to have dragonflight retail nameplates. Thank you for the addon :)

**Comment by Karl-HeinzSchneider** [comment]
Sure, you can move them there (or use one of the extra 6/7/8); basic setup would look like this:
![image](https://github.com/user-attachments/assets/8ced88e6-5659-4623-afff-a50afd212747)

All the textures look a bit different on retail, they have some kind of filter applied to them (I think). I use the exported textures from retail with the same values for size etc, but its not 1:1 in detail.

The main bar border is missing yeah, I might add it if I have downtime. 
Also moving everything is a big extra work atm, but I'm working on an editmode like retail has to visually drag them around the screen.

**Comment by Karl-HeinzSchneider** [comment]
And if you use the default bags, you can move the bag anchor if you want so see the side actionbars when the bags are open, like this: (in the Bag settings)
![image](https://github.com/user-attachments/assets/19907ee7-646f-4248-90b5-56facc4a0108)
You can play a bit with the values there.

**Comment by Niklan** [comment]
Yeah, that works, thank you. I've also moved Questtracker to avoid overlaping.

Are actionbar4 and actionbar5 correct? Because when I disable 'Action bar 4" in default game settings, the actionbar5 becomes invisible, and the same for "Action bar 5" - it changes the visibility of actionbar4 in the addon.

[Screencast from 2024-08-25 14-00-48.webm](https://github.com/user-attachments/assets/52320cb6-36dd-4c02-ac8f-fd35bfbb2514)

**Comment by Karl-HeinzSchneider** [comment]
Activate all actionbars in the blizzard options; if you dont need them, go into the DragonflightUI actionbar settings, scroll down to Visibility, and just check 'Always Hide'.
I'm reusing the default actionbars, but 4 and 5 are linked together through the settings, so you can only check 5 if 4 is checked. Just leave them all active, and use the addon options to hide them if you want.

**Comment by Niklan** [comment]
Yeah, I got that, but I think the action bar number is incorrect. The 'actionbar4' in DragonflightUI is controlled by "Action bar 5" in the game settings. Same for 'actionbar5', it is controlled by "Action bar 4" in the game settings. It's a little bit confusing, but not critical. This is why I didn't understand initially and looked at 'actionbar4', the "Action bar 5" was disabled in the game settings and settings from DragonflightUI in 'actionbar4' doesn't affect anything in that case. I had to enable "Action bar 5" to make it work.

| Game setting | DragonflightUI setting | Matches number |
| ------------ | ---------------------- | ------- |
| Action bar 1 | Actionbar1             | Yes  |
| Action bar 2 | Actionbar2             | Yes |
| Action bar 3 | Actionbar3             | Yes |
| Action bar 4 | Actionbar5             | No |
| Action bar 5 | Actionbar4             | No |

**Comment by Karl-HeinzSchneider** [comment]
Yeah, but the problem is the default naming of the buttons:
MultiBarLeftButton and MultiBarRightButton.
With my default setup, i logically? put the ones with MultiBar**Left**Button on the left side, but thats Actionbar5, because the first extra one (Actionbar4) you activate, is the right one on the side of the screen.

And for me it made more sense to have 4 on the left, because I would *read* them from left to right 4 <= 1-3 => 5

**Comment by Niklan** [comment]
Yeah, it makes sense. :+1: 

The main bug is fixed, so I close the issue as resolved. Thank you again, for response and addon.
