### ISSUE TITLE
[ERROR] LUA ERROR

### ISSUE THREAD

**Issue by SirFailaLot89** [Karl-HeinzSchneider/WoW-DragonflightUI#243]
As i was moving the Player frame this showed up:

>>>>Page 1/2<<<<

Message: Interface/AddOns/DragonflightUI/Config.lua:67: attempt to call method 'GetSubCategory' (a nil value)
Time: Sun Aug 25 20:14:12 2024
Count: 1
Stack: Interface/AddOns/DragonflightUI/Config.lua:67: attempt to call method 'GetSubCategory' (a nil value)
[string "@Interface/AddOns/DragonflightUI/Config.lua"]:67: in function `refreshCat'
[string "@Interface/AddOns/DragonflightUI/Config.lua"]:70: in function <Interface/AddOns/DragonflightUI/Config.lua:61>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `RefreshConfig'
[string "@Interface/AddOns/DragonflightUI/Config.lua"]:48: in function `?'
...
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:178: in function <...rface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua"]:529: in function `OnEntryClicked'
[string "@Interface/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua"]:544: in function <...e/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua:543>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:178: in function <...rface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua"]:610: in function <...e/AddOns/DragonflightUI/Mixin/SettingsList.mixin.lua:609>

Locals: name = "Profiles"
(*temporary) = nil
(*temporary) = DragonflightUIConfigFrame {
 0 = <userdata>
 selectedFrame = Frame {
 }
 InitCategorys = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:96
 Close = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:62
 ShowQuickKeybind = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:87
 ClosePanelButton = Button {
 }
 InnerFrame = Texture {
 }
 QuickKeybind = DragonflightUIQuickKeybindFrame {
 }
 DFCategoryList = Frame {
 }
 Bg = Frame {
 }
 Container = Frame {
 }
 selected = true
 NineSlice = Frame {
 }
 OnLoad = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:8
 OnHide = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:54
 KeybindButton = Button {
 }
 RefreshCatSub = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:213
 OnEvent = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:58
 MinimizeButton = Button {
 }
 InitQuickKeybind = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:76
 OutputText = FontString {
 }
 CloseButton = Button {
 }
 MaxMinButtonFrame = Button {
 }
 OnShow = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:43
 Minimize = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:66
 OnSelectionChanged = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:186
}
(*temporary) = "General"
(*temporary) = "Profiles"
(*temporary) = "attempt to call method 'GetSubCategory' (a nil value)"
configFrame = DragonflightUIConfigFrame {
 0 = <userdata>
 selectedFrame = Frame {
 }
 InitCategorys = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:96
 Close = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:62
 ShowQuickKeybind = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Config.mixin.lua:87
 ClosePanelButton = Button {
 }
 InnerFrame = Texture {
 }
 QuickKeybind = DragonflightUIQuickKeybindFrame {
 }
 DFCategoryList = Frame {
 }
 Bg = Frame {
 }
 Container = Frame {
 }
 selected = true
 NineSlice = Frame {
 }
 OnLoad = <function> defined @Interface/AddOns/DragonflightUI/

>>>>Page 2/2<<<<

Message: DragonflightUITargetCastbar:SetPoint(): Usage: ("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY]
Time: Sun Aug 25 20:14:24 2024
Count: 1
Stack: DragonflightUITargetCastbar:SetPoint(): Usage: ("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY]
[string "=[C]"]: in function `SetPoint'
[string "@Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua"]:673: in function `AdjustPosition'
[string "@Interface/AddOns/DragonflightUI/Modules/Castbar.lua"]:785: in function <Interface/AddOns/DragonflightUI/Modules/Castbar.lua:783>
[string "=[C]"]: in function `Target_Spellbar_AdjustPosition'
[string "@Interface/AddOns/Blizzard_UnitFrame/Vanilla/TargetFrame.lua"]:629: in function `TargetFrame_UpdateAuras'
[string "@Interface/AddOns/Blizzard_UnitFrame/Vanilla/TargetFrame.lua"]:147: in function `TargetFrame_Update'
[string "@Interface/AddOns/Blizzard_UnitFrame/Vanilla/TargetFrame.lua"]:166: in function <...ce/AddOns/Blizzard_UnitFrame/Vanilla/TargetFrame.lua:158>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/AddOns/Blizzard_FrameXML/Classic/SecureTemplates.lua"]:493: in function `handler'
[string "@Interface/AddOns/Blizzard_FrameXML/Classic/SecureTemplates.lua"]:633: in function `SecureActionButton_OnClick'
[string "@Interface/AddOns/Blizzard_FrameXML/Classic/SecureTemplates.lua"]:673: in function <...AddOns/Blizzard_FrameXML/Classic/SecureTemplates.lua:665>

Locals: (*temporary) = DragonflightUITargetCastbar {
 0 = <userdata>
 SetCastTimeTextShown = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:521
 CastTimeText = FontString {
 }
 HideSpark = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:440
 SetShowTicks = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:615
 ShowSpark = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:433
 Flash = Texture {
 }
 showIcon = true
 HandleInterruptOrSpellFailed = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:397
 SetUnit = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:232
 AddTickTable = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:599
 AdjustPosition = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:651
 OnUpdate = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:284
 SetShowRank = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:619
 showCastTimeMaxSetting = false
 showCastTimeSetting = true
 GetTickCount = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:607
 showTradeSkills = true
 preci = 1
 UpdateState = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:623
 showRank = false
 AddTicks = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:579
 state = <table> {
 }
 fadeOut = true
 unit = "target"
 FinishSpell = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:551
 showShield = false
 UpdateShownState = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:493
 DropShadow = Texture {
 }
 preciMax = 2
 showTicks = false
 UpdateCastTimeText = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:444
 ticks = <table> {
 }
 CastTimeTextCompact = FontString {
 }
 SetCompactLayout = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:481
 UpdateCastTimeTextShown = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:536
 HideAllTicks = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:595
 UpdateIsShown = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:512
 flash = true
 showCastbar = true
 holdTime = 8033.939000
 SetIconShown = <function> defined @Interface/AddOns/DragonflightUI/Mixin/Castbar.mixin.lua:531
 SetPrecision = <funct

**Comment by Karl-HeinzSchneider** [comment]
Hey,
thanks for the report.
Somehow this never got noticed, but I spotted it yesterday while changing profiles. Should be fixed with 22df3ebdcdccefda787e355fb55316bcef3b5ec9
