### ISSUE TITLE
[BUG] Flight map has a bad scaling

### ISSUE THREAD

**Issue by abgonzalez93** [Karl-HeinzSchneider/WoW-DragonflightUI#245]
**Describe the bug**
The flight map has a bad scaling. The flght points are not where they're supposed to be.

![imagen](https://github.com/user-attachments/assets/83015d5e-60a5-4203-9ba1-ffb67bb0eb16)

If you see the image, Southshore is on Wetlands and Stormwind is on Westfall... It makes no sense.
Is there any way to fix this inside the addon? Maybe disabling Flight map window like Skills or Talents window?

**Comment by Karl-HeinzSchneider** [comment]
Hey,
sorry, it's already fixed for the next version, was just holding off for some other feature. I'll push it tonight, or tomorrow.

See 441e204cbd5a14e73097821d905e285b2c6bff71
(I tried to remove the taint, but it seems there isnt any other way, but there weren't any errors or something like that with this solution)

**Comment by Karl-HeinzSchneider** [comment]
Fixed with v0.16.1
