### ISSUE TITLE
[BUG] In SoD, XPBar at max level shows 69%

### ISSUE THREAD

**Issue by akatechis** [Karl-HeinzSchneider/WoW-DragonflightUI#250]
**Describe the bug**
![image](https://github.com/user-attachments/assets/4ef3b91d-ebe4-42eb-b1fe-f6e74801192d)

In SoD, I have a level 60 character, and the XPbar is showing at 69%.

**Error Log**
I dont see any bugs related to DragonflightUI

**Versions (please complete the following information):**
 - WoW: `SoD 1.15.3.55917`
 - Addon `0.16.1`

**Additional context**

**Comment by Karl-HeinzSchneider** [comment]
Ah, sorry, I think I know why that is: I added the visibility state handler, the generic one like on the other frames, but didn't consider adding logic to deactivate this when you are max level. 
I'll fix it, and push out a new version today.

**Comment by Karl-HeinzSchneider** [comment]
v0.16.2 on curseforge in ~15min
