### ISSUE TITLE
[BUG] Cast bars do not appear if you're not targeting an enemy

### ISSUE THREAD

**Issue by abgonzalez93** [Karl-HeinzSchneider/WoW-DragonflightUI#252]
If an enemy casts an ability and you target him after that, the cast bar does not appear.
If he casts again and you're already targeting him, the cast bar appears.

![Captura de pantalla 2024-09-03 174006](https://github.com/user-attachments/assets/ee5297c9-4b87-4e77-bcbb-10f7539a6a4c)

There're some bugs about the cast bar + target that gotta be fixed; which are critical in some situations.

**Comment by Karl-HeinzSchneider** [comment]
Fixed with 608ce6c02e93b43332cb170db87807a0d152cf36
Will push the update to curseforge later
