### ISSUE TITLE
[BUG] Castbar disappearing is delayed by a full second.

### ISSUE THREAD

**Issue by flannerby** [Karl-HeinzSchneider/WoW-DragonflightUI#265]
**Describe the bug**
After casting there is a sizeable delay before the bar goes away. The vanilla bar goes away almost immediately after casting is completed.

**Versions (please complete the following information):**
 - WoW: 1.15.4 (56817)
 - Addon: 0.17.1

**Comment by Karl-HeinzSchneider** [comment]
Intended. Uses global variable `CASTING_BAR_HOLD_TIME`
You can change it by `/run CASTING_BAR_HOLD_TIME=0.1`  etc. But you have to set that after each reload, so easiest would be a small WA which sets this after reload.
