### ISSUE TITLE
Mixin - SettingsList LUA Error

### ISSUE THREAD

**Issue by mootkins** [Karl-HeinzSchneider/WoW-DragonflightUI#266]
1x ...eDragonflightUI/Mixin/SettingsList.mixin.lua:347: attempt to call global 'GetMouseFocus' (a nil value)
[string "@DragonflightUI/Mixin/SettingsList.mixin.lua"]:347: in function `HidePopout'
[string "@DragonflightUI/Mixin/SettingsList.mixin.lua"]:334: in function `TogglePopout'
[string "@DragonflightUI/Mixin/SettingsList.mixin.lua"]:313: in function <...eDragonflightUI/Mixin/SettingsList.mixin.lua:312>

Locals:
self = Button {
 HighlightTexture = Texture {
 }
 SelectionDetails = Frame {
 }
 parent = Frame {
 }
 callbackTables = <table> {
 }
 NormalTexture = Texture {
 }
 selectionEntryTemplates = "SettingsSelectionPopoutEntryTemplate"
 Popout = Frame {
 }
 Event = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMouseFocus' (a nil value)"

**Comment by Karl-HeinzSchneider** [comment]
Fixed in new version with f9e3bf40cbeda916cda7f4c60458a55496d2c2b0 (later on curseforge)
