### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FenaLoves** [Karl-HeinzSchneider/WoW-DragonflightUI#274]
UI error in Anniversary Classic realms, Spanish LA

Error Logs:

Message: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:216: attempt to index local 'state' (a nil value)
Time: Fri Nov 22 03:45:59 2024
Count: 1
Stack: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:216: attempt to index local 'state' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:216: in function `UpdateText'
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:178: in function `Update'
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:24: in function <...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:23>

Locals: 

Message: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:379: attempt to index local 'state' (a nil value)
Time: Fri Nov 22 03:45:59 2024
Count: 1
Stack: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:379: attempt to index local 'state' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:379: in function `Update'
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:308: in function <...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:307>

Locals: 

Message: ...face/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua:114: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DragonflightUIActionbarFrame3:SetPoint.
Time: Fri Nov 22 03:45:59 2024
Count: 1
Stack: ...face/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua:114: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DragonflightUIActionbarFrame3:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua"]:114: in function `Update'
[string "@Interface/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua"]:36: in function <...face/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua:35>

Locals: (*temporary) = DragonflightUIActionbarFrame3 {
 mask = MaskTexture {
 }
 savedAlwaysShow = true
 box = Frame {
 }
 state = <table> {
 }
 DFShower = DragonflightUIActionbarFrame3Shower {
 }
 buttonTable = <table> {
 }
 stanceBar = false
 DFMouseHandler = DragonflightUIActionbarFrame3HandlerOnEnterLeave {
 }
 DFStateHandler = DragonflightUIActionbarFrame3Handler {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = DragonflightUIActionbarFrame2 {
 mask = MaskTexture {
 }
 savedAlwaysShow = true
 box = Frame {
 }
 state = <table> {
 }
 DFShower = DragonflightUIActionbarFrame2Shower {
 }
 buttonTable = <table> {
 }
 stanceBar = false
 DFMouseHandler = DragonflightUIActionbarFrame2HandlerOnEnterLeave {
 }
 DFStateHandler = DragonflightUIActionbarFrame2Handler {
 }
}
(*temporary) = "TOP"
(*temporary) = 0
(*temporary) = 0

Message: ...face/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua:77: attempt to index local 'state' (a nil value)
Time: Fri Nov 22 03:45:59 2024
Count: 6
Stack: ...face/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua:77: attempt to index local 'state' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua"]:77: in function `Update'
[string "@Interface/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua"]:36: in function <...face/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua:35>

Locals: 

Message: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:379: attempt to index local 'state' (a nil value)
Time: Fri Nov 22 03:46:02 2024
Count: 1
Stack: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:379: attempt to index local 'state' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:379: in function `Update'
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:308: in function <...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:307>
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/Libs/ThreadLib.lua"]:37: in function <Interface/AddOns/Questie/Modules/Libs/ThreadLib.lua:35>

Locals: 
**Versions:**
 - WoW: [Anniversary Realms]
 - Addon [e.g. v0.19.1]

**Additional context**

**Comment by Karl-HeinzSchneider** [comment]
Hey,
I think the problem is, you changed the frame anchor for some actionbars, and they formed a loop, e.g.  bar1 => bar2 => bar3 => bar1
```
Locals:

Message: ...face/AddOns/DragonflightUI/Mixin/Actionbar.mixin.lua:114: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DragonflightUIActionbarFrame3:SetPoint.
```

I did implement some checks for that, but it might still be possible. 

If the ingame menu is working, you should look at those anchors and change them, the error suggests something with Actionbar3. If they bug out, you could exit wow completely, and then edit the `WTF > Account > *yourAccount* > SavedVariables > DragonflightUI.lua`. Are you familiar with the format? (Its based on the Ace3 framework, so every entry is basically a difference to the default settings, so you could edit out your changes to the anchors and the will be default again)

At least thats my first idea based on the messages.
