### ISSUE TITLE
[BUG] In SOD, talent button re-appears when I press ESC

### ISSUE THREAD

**Issue by akatechis** [Karl-HeinzSchneider/WoW-DragonflightUI#281]
**Describe the bug**
See screenshot

<img width="998" alt="image" src="https://github.com/user-attachments/assets/50b3afd6-f08e-4d80-a531-8d41c333fd9c">

**Error Log**
Please provide any lua error you encounter. Make sure you have error reporting enabled ingame ('/console scriptErrors 1'). Also consider using [BugSack](https://www.curseforge.com/wow/addons/bugsack) **and** [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber).

**Versions (please complete the following information):**
 - WoW: SoD
 - Addon: 0.19.5

**Additional context**
If I go into the menu, uncheck "hide" and then check it again, it will go away. Then, if I press ESC, the Talent button re-appears.

https://github.com/user-attachments/assets/22cc112a-a6c3-40f0-a077-c022dda49938

I have only tested in SOD, I'm not sure if ERA/Anniversary have the same issue.

**Comment by Karl-HeinzSchneider** [comment]
Ah, I see! 
Problem is, blizzard overrides this a ton, I might have to dig more into the code again. Also the new options with different guild windows as buttons on the micromenu is a bit of a headache.
I'll look into it later or tomorrow, and see if its a quick fix or needs more work.

**Comment by Karl-HeinzSchneider** [comment]
Fixed in the new version, out soon.
Cant hide it in combat, so it will update as soon as you leave combat again.
