### ISSUE TITLE
[BUG] Player Frame class color  (Classic Era)

### ISSUE THREAD

**Issue by edizmetin** [Karl-HeinzSchneider/WoW-DragonflightUI#283]
The class color option on the Player Frame doesn't always work as intended. Usually, the health bar displays the class color, but sometimes during combat, it reverts to the default green color. I will attach a short video at the end of this report for reference. The video was recorded with only the Dragonflight UI addon active, and there are no BugSack errors.

https://github.com/user-attachments/assets/a2aa5981-ea23-44a3-9d17-6b3f6516a528

**Comment by Karl-HeinzSchneider** [comment]
The statusbar color gets overriden quite often in the default blizzard code, and it seems like its missing a hook where that happens to override it again. Does this happen often? It seems like it happend as the mana bar gets to 100%, and maybe the playerframe does a complete update then.
I'll investigate a bit more.

**Comment by Karl-HeinzSchneider** [comment]
I can't reproduce this, but I added some more hooks to fix the class color; it gets called a lot, but should not cause any problems as the function call is quite light: 387b6c820992c5b3a6222d181ee1aca2dbbc8bf0

**Comment by Karl-HeinzSchneider** [comment]
v0.19.6 live on curseforge.
