### ISSUE TITLE
[Feature Request] Add dark mode to party/raid unitframes

### ISSUE THREAD

**Issue by akatechis** [Karl-HeinzSchneider/WoW-DragonflightUI#287]
**Is your feature request related to a problem? Please describe.**
Would love to make my raid frames match the rest of my UI, using dark mode to choose RGB values.

**Describe the solution you'd like**
I would like the raid frames' outline color to be customizable. Haven't tried party frames, because I use raid frames for party anyway, but would be nice for that to be available to people who use party frames.

**Additional context**
![image](https://github.com/user-attachments/assets/e98695d4-9bc8-4b12-9bcf-09c7f4cf44ba)

**Comment by akatechis** [comment]
Not sure if I should make a separate issue for this, but I just noticed the tracking icon's border also isn't recolored, but the LFG icon's border IS.

![image](https://github.com/user-attachments/assets/0f252baf-abe0-41ec-9596-bd2d16a1b5c4)

**Comment by Karl-HeinzSchneider** [comment]
Hey,
I'm not touching the raidframes at all at the moment, so I might not do something with them like a dark mode. 

They party is missing, yeah. I cant really test atm, but this should work: b0232aab0ca53f417067e29a2a9c143a37a6ed3e

I also fixed the tracking border: 22ea2cd7717e61ff66691f05fad19d56093dac01
