### ISSUE TITLE
[BUG] Dressing Room UI elements out of place when using "Enhance Dressup" option of Leatrix Plus addon

### ISSUE THREAD

**Issue by zarecpa2** [Karl-HeinzSchneider/WoW-DragonflightUI#289]
Hello, 
first of all, incredible addon, and I understand that my issue is basically out of scope and one can't expect the addon to work with plethora of others. Still, I'd like to point out the following issue of the Dressup window when interacting with the addon Leatrix Plus.

**Bug Description**
When both Dragonflight UI and Leatrix's enhance dressup addons are enabled, UI elements of the dressup are moved closer to the middle of the window instead of being at the bottom, and the entire preview shrinks, as visible on following screenshots:

Dragonflight UI disabled             |  Dragonflight UI enabled
:-------------------------:|:-------------------------:
![Snímek obrazovky 2024-12-10 065433](https://github.com/user-attachments/assets/d3298ecb-804c-40f8-a277-863819d88d41) |  ![Snímek obrazovky 2024-12-10 065410](https://github.com/user-attachments/assets/900053eb-b32d-4d7c-a2f6-5a931e93b662)

**Error Log**
No Lua error is thrown

**Versions (please complete the following information):**
 - WoW: Cata classic
 - Dragonflight UI Classic v0.19.11
 - Leatrix Plus 4.0.37

**Additional context**
As a workaround, I am simply commenting the module out in UI.lua:
` -- DragonflightUIMixin:ChangeDressupFrame()`

**Comment by Karl-HeinzSchneider** [comment]
Hey,
its kinda out of scope, yes, but LeatrixPlus is one of the most used addons, so I might add some compatibility for it like for other options/addons. I have not used this option, but will check it out and see what I can do.

**Comment by Karl-HeinzSchneider** [comment]
I don't think the work to do a 100% compatibility is worth it; I just improved the default dressup frame with the most used function: mousewheel zoom and panning, see 78e64b46003b1fa7c3cd20f4882056c4c0e08326
