### ISSUE TITLE
[BUG] GCD radial indicator doesn't cover the entire button

### ISSUE THREAD

**Issue by akatechis** [Karl-HeinzSchneider/WoW-DragonflightUI#291]
**Describe the bug**
When I press a skill and the GCD is up, the radial indicator for GCD leaves a few pixels of space where it doesn't shade the ability. Most noticeable, in my screenshot, is Flanking Strike, Wing clip and Immolation trap. You can also notice it a lot in aspect of the falcon, cheetah and wild in the 3rd action bar.

![image](https://github.com/user-attachments/assets/da4b4d4a-e4e0-4fdc-bb07-38ab47c98e7e)

**Error Log**
Please provide any lua error you encounter. Make sure you have error reporting enabled ingame ('/console scriptErrors 1'). Also consider using [BugSack](https://www.curseforge.com/wow/addons/bugsack) **and** [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber).

**Versions (please complete the following information):**
 - WoW: SoD latest
 - Addon: 0.19.12

**Comment by Karl-HeinzSchneider** [comment]
I did already tweak it a bit more with 21d0f64575198d302a3af786aacb6b2ebb3845f0
Will push the update now, should be on curseforge in about 15min.
