### ISSUE TITLE
[BUG] Error with Minimap Alert addon

### ISSUE THREAD

**Issue by brutzel** [Karl-HeinzSchneider/WoW-DragonflightUI#293]
**Describe the bug**
The addon Minimap Alert constantly scans for herbs and mining nodes by resizing the minimap and moving it along the cursor position and back to its origin to trigger minimap tooltips. This was compatible with DragonflightUI a while ago but then it broke. When I enter combat I get the lua error below.

To reproduce

- Install both addons
- run `/minimapalert`
- Hit Start
- Enter combat
- See error below

I will make another donation if this gets fixed 😎

**Error Log**
```
Message: Minimap:SetPoint(): Usage: ("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY]
Time: Sun Dec 15 02:42:22 2024
Count: 1
Stack: Minimap:SetPoint(): Usage: ("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY]
[string "@Interface/AddOns/Minimap_Alert/Minimap_Alert.lua"]:239: in function <Interface/AddOns/Minimap_Alert/Minimap_Alert.lua:234>
[string "@Interface/AddOns/Minimap_Alert/Minimap_Alert.lua"]:536: in function `?'
[string "@Interface/AddOns/Minimap_Alert/Minimap_Alert.lua"]:20: in function <Interface/AddOns/Minimap_Alert/Minimap_Alert.lua:17>
[string "@Interface/AddOns/Minimap_Alert/Minimap_Alert.lua"]:448: in function <Interface/AddOns/Minimap_Alert/Minimap_Alert.lua:412>
```

**Versions (please complete the following information):**
 - WoW: Era
 - Addon 0.19.13 with Minimap Alert 26

**Additional context**

**Comment by Karl-HeinzSchneider** [comment]
When did it work? I have not really touched the minimap in the latest updates. The last big change was like 2 months ago when I introduced the state handler to hide frames out of combat etc.

**Comment by Karl-HeinzSchneider** [comment]
Should be fixed with 8996da696fd22f3425ff5921fc64f3afc48afda3

You need to disable this setting inside minimap _and_ buff settings: 
![image](https://github.com/user-attachments/assets/9b0bc15b-ee6f-4d8f-93c0-168dc170e64b)
(and /reload)

I will push out the update later, might do 1-2 more fixes for this version.

**Comment by brutzel** [comment]
That fix came fast, thanks! I went back checking older versions with CurseForge client and the first broken version with those two addons seems to be 0.16.2 when entering combat. It is another error message though. That version is hardly compatible with latest era client so I don't know if the root cause is there.

```
Message: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:182: attempt to index local 'state' (a nil value)
Time: Mon Dec 16 10:49:12 2024
Count: 2
Stack: ...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:182: attempt to index local 'state' (a nil value)
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:182: in function `Update'
[string "@Interface/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua"]:24: in function <...face/AddOns/DragonflightUI/Mixin/Statusbar.mixin.lua:23>
```

Anyway, looking forward to a new release with that option!

**Comment by Karl-HeinzSchneider** [comment]
It was the state handler; I added those to hide frames based on macro conditionals, even in combat, but they make the frames secure.
Your addon moves the minimap around a lot, even in combat, which seems fine, but not with secure frames attached, so some calls get protected and will error out. 

My solution is not the best as I dont really like *too* many options, thats why I kind of buried it there on the end 😁

**Comment by Karl-HeinzSchneider** [comment]
[v0.19.14](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/releases/tag/v0.19.14)
You can get it here, or wait for curseforge (they take like 15-30min to approve)

**Comment by brutzel** [comment]
Thank you very much, 0.19.14 fixed it 😊 Donation incoming 💵💵💵

Just FYI it still says `Interface action failed because of an AddOn` when scanning+entering combat but no Lua error. But MinimapAlert is working fine now so I don't really care.

**Comment by Karl-HeinzSchneider** [comment]
Thanks! Feel free to open another issue for anything you notice, or if you have suggestions.

Enjoy the holidays! ❤🎄
