### ISSUE TITLE
Turtle WOW issues

### ISSUE THREAD

**Issue by RedJohnlol** [Karl-HeinzSchneider/WoW-DragonflightUI#33]
Hello, 
This addon is pretty great！
You may already be aware that Blizzard Entertainment has exited the Chinese market...temporarily I hope.
Tens of thousands of Chinese players are playing Turtle WoW.
Wish this could be updated for Turtle WOW version 1.17.0, if possible.
Thanks .

**Comment by Karl-HeinzSchneider** [comment]
Isn't Turtle WoW using an old client version? I won't work on old version, but updating should be possible. 
Have you tried the [backported 3.3.5a Version somebody made](https://github.com/yuritsuki/WoW-DragonflightUI)?

**Comment by RedJohnlol** [comment]
> Isn't Turtle WoW using an old client version? I won't work on old version, but updating should be possible. Have you tried the [backported 3.3.5a Version somebody made](https://github.com/yuritsuki/WoW-DragonflightUI)?

It doesn't work...thanks anyway
