### ISSUE TITLE
[Feature Request] Action bar resizing

### ISSUE THREAD

**Issue by z0n** [Karl-HeinzSchneider/WoW-DragonflightUI#34]
Hi, thanks for this great addon! Not sure if this is out of scope but I have a request regarding action bar resizing. The option to move the right bars to the sides is great, however I'd like to change the size of these action bars to 2x5 instead of 3x4.  
I tried using other addons for this (e.g. Dominos and Bartender) but it seems like they all completely replace the default action bars which means I can't use the DFUI bars at all. Any advice is appreciated 😄

**Comment by Karl-HeinzSchneider** [comment]
You mean 2x6? Or would you just not use the 2 remaining buttons? Maybe screenspace becomes a problem i guess.
Changing the position of the buttons is not too difficult. Most work would be to add the interface options for it. I might do it for the next bigger update, which will come out in like a week.

**Comment by z0n** [comment]
Correct, I'm only using 10 buttons in a 2x5 grid. That's my retail setup and I kinda got used to it 😄

**Comment by Karl-HeinzSchneider** [comment]
Check out the new Update! 😁

**Comment by z0n** [comment]
Nice one!
