### ISSUE TITLE
Class color stops working for a moment

### ISSUE THREAD

**Issue by Hessutar** [Karl-HeinzSchneider/WoW-DragonflightUI#42]
Heya!

Noticed some weird behavior for the class color on player unitframe.

When I swap to bear form with my druid, the hp bar changes green but when I for example target my self, the bar turns back to class color.

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/5693510/9d6f1a6c-05fd-405b-99a6-a3da5d5db26f)

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/5693510/b25fd7ec-53b9-44e1-95a2-f477ddef2051)

Taking damage or healing/hp regen seems to fix the color as well. Maybe it is somehow tied to something triggering an event?

**Comment by Karl-HeinzSchneider** [comment]
Hey,
thanks for the good bug report!
Was an easy fix: the unitevent 'UNIT_MAXHEALTH' was overriding the Vertexcolor.
Should be fixed in the next update (or you update yourself through the latest github version)
