### ISSUE TITLE
Feature Request: exp bar as it's own option

### ISSUE THREAD

**Issue by Renari** [Karl-HeinzSchneider/WoW-DragonflightUI#43]
It would be nice if we could enable the DF exp bar but not have it be bundled with the action bars.

**Comment by Karl-HeinzSchneider** [comment]
Would you use another Actionbar addon, or just different Size/Position etc?

**Comment by Karl-HeinzSchneider** [comment]
New Update sneak peak:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/f2106e67-205c-4162-80e5-602e50a077da)
(I think i missed a setting for size_x and size_y, will include that later!)

Would you need more options?

**Comment by Renari** [comment]
Hard to say without messing with hit, this is what I have now:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/1839179/979fe51d-118a-45d0-ac00-07de7a227819)
