### ISSUE TITLE
Player unit frame messes up when zoning into deadmines

### ISSUE THREAD

**Issue by Renari** [Karl-HeinzSchneider/WoW-DragonflightUI#44]
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/1839179/f255a240-6d2a-4394-8abe-874591675102)

`/reload` fixes it

**Comment by Renari** [comment]
It seems this only happens in Dead Mines?

**Comment by Karl-HeinzSchneider** [comment]
Should be fixed in the next Version! 
Thanks for reporting.
