### ISSUE TITLE
Feature request: Five Second Rule 

### ISSUE THREAD

**Issue by Hessutar** [Karl-HeinzSchneider/WoW-DragonflightUI#45]
Hello!

Would it be possible to implement a five second rule to the mana bar or somewhere on the player unitframe? Maybe a spark or something to move across the mana bar?

**Comment by Karl-HeinzSchneider** [comment]
I'll take a look at that if i have time! (Living the warrior dream on SoD, so no mana 😁)

**Comment by Hessutar** [comment]
Actually found a mp5 spark addon that seems to work pretty good with DFUI.
I'll link it here if someone is also looking for a mp5 spark addon.
https://www.curseforge.com/wow/addons/zulspark/comments
