### ISSUE TITLE
Leave vehicle button anchoring

### ISSUE THREAD

**Issue by Hessutar** [Karl-HeinzSchneider/WoW-DragonflightUI#46]
Hello again!

Noticed a minor cosmetic defect of the leave button anchoring.

With my shaman it is on top of the chat.

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/5693510/f2342493-3c5d-47f1-ba2a-29daab7b0677)

But with my druid which has a stance bar it seems to anchor properly on top of the actions bars.

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/5693510/4bf5a155-a15b-43d0-b793-06a06bb4e6a8)

**Comment by Karl-HeinzSchneider** [comment]
Are you using any Addon for your Totembar?
On my shaman its working like it should: 
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/a2309e3c-f32f-46ea-8fbc-10b5e5bbdd3d)

It gets set from Blizzard in 
```
function MainMenuBarVehicleLeaveButton_Update()
	if ( ( CanExitVehicle() or UnitOnTaxi("player")) and ActionBarController_GetCurrentActionBarState() == LE_ACTIONBAR_STATE_MAIN ) then
		MainMenuBarVehicleLeaveButton:ClearAllPoints();
		if ( IsPossessBarVisible() ) then
			MainMenuBarVehicleLeaveButton:SetPoint("LEFT", PossessButton2, "RIGHT", 30, 0);
		elseif ( GetNumShapeshiftForms() > 0 ) then
			MainMenuBarVehicleLeaveButton:SetPoint("LEFT", StanceBarFrame.StanceButtons[GetNumShapeshiftForms()], "RIGHT", 30, 0);
		elseif ( MultiCastActionBarFrame and HasMultiCastActionBar() ) then
			MainMenuBarVehicleLeaveButton:SetPoint("LEFT", MultiCastActionBarFrame, "RIGHT", 30, 0);
		else
			MainMenuBarVehicleLeaveButton:SetPoint("LEFT", PossessBarFrame, "LEFT", 10, 0);
		end

		MainMenuBarVehicleLeaveButton:Show();
		MainMenuBarVehicleLeaveButton:Enable();
		ShowPetActionBar(true);
	else
		MainMenuBarVehicleLeaveButton:SetHighlightTexture([[Interface\Buttons\ButtonHilight-Square]], "ADD");
		MainMenuBarVehicleLeaveButton:UnlockHighlight();
		MainMenuBarVehicleLeaveButton:Hide();
		ShowPetActionBar(true);
	end

	UIParent_ManageFramePositions();
end
```

and shaman is this case:

```
elseif ( MultiCastActionBarFrame and HasMultiCastActionBar() ) then
			MainMenuBarVehicleLeaveButton:SetPoint("LEFT", MultiCastActionBarFrame, "RIGHT", 30, 0);
```

**Comment by Hessutar** [comment]
You are correct, I am using TotemTimers addon for my totems. I tried to disable it but couldn't get my totem bar to show as you have it. I wonder if there is a totem bar in classic as it seems to be in classic wrath (I asume)?

**Comment by Karl-HeinzSchneider** [comment]
Hm, maybe its an Era problem?
on Wrath it seems to work for me:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/90a02ee3-9e4c-46a5-9bb4-3549a84fdb65)
I guess i need to lvl a shaman then.

I'll try to investigate if I have time.

**Comment by Karl-HeinzSchneider** [comment]
I think i know what the issue was. Made a change for the next major version. But i don't have a shaman on Era, so you might have to test for me 😁

**Comment by MrGMYT** [comment]
This also seems to be happening on flight paths on my Hunter

**Comment by Hessutar** [comment]
> I think i know what the issue was. Made a change for the next major version. But i don't have a shaman on Era, so you might have to test for me 😁

Sure no problem!

**Comment by Laidbak83** [comment]
Hello, before all thanks for this amazing addon <3
i'm using mage and i have the bug too
![Uploading Capture.PNG…]()

**Comment by Laidbak83** [comment]
![Capture](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/10518667/5c2f9b07-5a93-4e11-823a-d907197d6049)

**Comment by Karl-HeinzSchneider** [comment]
I pushed a small fix for the next version. 
All classes with stance bars should work fine at the moment, but others like Mage need the fix. (I dont have a char without stance bar to test atm😅).
