### ISSUE TITLE
Option for no Art on main action bar.

### ISSUE THREAD

**Issue by MrGMYT** [Karl-HeinzSchneider/WoW-DragonflightUI#47]
This is something that you can do in Dragonflight. Basically just remove the art in the boxes for the main action bar to make it look like the reset of the bars

Thank you for your hard work, its very appreciated

**Comment by Karl-HeinzSchneider** [comment]
If you mean the Gryphons, you can deactivate those through the Interface Options -> 
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/f700499a-0c5f-4ffb-954e-c87d268377ce)

But maybe you mean the grey box background of each actionbutton? Then theres not really an option right now.
(You could comment out 'Module.DrawActionbarDeco()' in Actionbar.lua, but its not really great)

I'm working an a new and way better customization menu, so maybe i will add this as an option.

**Comment by MrGMYT** [comment]
Sorry, I should've added a picture! 

I mean this bar down the bottom. Mainly because in SOD we don't have enough spells to fill the entire bar (at least I don't) so it looks a bit mismatched having the empty buttons. Plus this is an option available in Dragonflight.

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/29455493/9c2e7eda-bb14-4cf8-af5d-28496ff38e28)

**Comment by Karl-HeinzSchneider** [comment]
Next major version includes more options:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/4f0e26af-ee17-4a3c-b312-3e53e97af108)
Buttonstyle etc was more like a temporary solution from one of the first versions, but after the holidays i will overhaul the complete system and match the retail aesthetics.
