### ISSUE TITLE
Minimap (in SoD)

### ISSUE THREAD

**Issue by Motrish** [Karl-HeinzSchneider/WoW-DragonflightUI#49]
Hi, this happens all the time. 

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/10175345/1c623542-b09a-47bc-9c9d-49fbdf4c6f20)

disabling -> reload -> fixed -> a few reloads later -> broken again

Scale 1.1
X -25 
Y -205

**Comment by Karl-HeinzSchneider** [comment]
I think you are using LeatrixPlus.
Just deactivate 'Enhance Minimap'.

**Comment by Motrish** [comment]
Bistn Gott ;D 
Gutes Addon ;)

**Comment by Motrish** [comment]
Bistn Gott ;D
Gutes Addon ;)
