### ISSUE TITLE
Aura duration of Buffs arent shown in classic SoD 

### ISSUE THREAD

**Issue by jobackman** [Karl-HeinzSchneider/WoW-DragonflightUI#50]
The targetframe doesnt display the duration spiral even though the duration information is seemingly available

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/732505/be61ef71-1dd2-4fb3-bf70-03c54d96cdc9)
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/732505/dbd0d417-dc44-4905-b723-3f6a7d85c09d)

**Comment by Karl-HeinzSchneider** [comment]
I'm not really touching Buffs (right now), so it just shows like the default UI. You need something like ClassicAuraDurations, but i think its not really updated for SoD 😐
I'll take a look if i have time, i also noticed this while playing SoD.

**Comment by jobackman** [comment]
Ah I see, so I guess it inherits from the default target frames that makes sense! 
I'll see if a separate addon like classicAuraDurations would fix this :) 

Also big props to you for doing this retail ui addon, I love it! 🥳

**Comment by Karl-HeinzSchneider** [comment]
I'm also using ClassicAuraDurations now, and it seems to work fine. 
If you have other suggestions or bugs, just open another issue. Thanks!
