### ISSUE TITLE
Request: Bigdebuffs support

### ISSUE THREAD

**Issue by dabadoo** [Karl-HeinzSchneider/WoW-DragonflightUI#52]
Would be awesome if we could get bigdebuffs support for the unitframes.

**Comment by Karl-HeinzSchneider** [comment]
Hey,
somebody also requested that a few weeks ago, so i took a look:
What from the addon isn't compatible?
I know the addon, but I'm not currently using it, so my quick test with default options:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/90a09826-5694-4ac8-91a8-f64a8cd7278d)
Seems fine for me, but I'm not sure. 
 
If something is buggy/off/not working, screenshots would be nice with a quick info how i can reproduce that. Most of my frames are default, only changed in size and textures, so most addons should be compatible (if they dont also change size, anchors etc)

**Comment by dabadoo** [comment]
Classic SoD:
I log on my priest and target myself and then buff power word shield.
![picture 1 casted PWS](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/25304408/7356a877-7702-4f04-9886-ee39c63f5685)
Looks like it works. But then when I change target or just deselect myself, the aura on my player frame goes away.
![picture 2 target someone else](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/25304408/fc49a3dc-264c-4c98-8e47-23ceae925a91)
The only thing remaining on my player icon is the cooldown text.
If I then retarget myself the aura on my player frame is still missing and only showing text
![retarget myself](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/25304408/b1fd7d55-b960-4a1b-80aa-4f56f59f3c72)
----
I also tried casting some CC on random mobs on my druid. I've previously experienced the same thing happening. The CC text duration appeared on the target mobs portrait but the aura icon didn't appear.
This "bug" did not happen from my quick test just now so I am unsure how to replicate it.
----
This might not just be a bigdebuff issue then. I think it also happned when I previously tested using LoseControl or ClassicAuraDurations for portrait auras. Sometimes it works but other times no icon appears and only text.

**Comment by dabadoo** [comment]
![hibernate](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/25304408/c310a276-4a9e-471a-8ded-fec841c77062)
I tried disabling bidebuffs and enabled classucauradurations and the same thing happned. Text but no icon.
I then tried disabling this addon and with classicauradurations only and it worked as expected
![Skærmbillede 2023-12-15 101034](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/25304408/ebd56343-33c0-4cd7-94f2-1acded33c1be)

**Comment by Karl-HeinzSchneider** [comment]
Ah hmm. Im resetting some things on player/target frame after target change, because blizzard overrides a lot of stuff and this was a quick fix for the rare situations something got overriden, and also a way to fix everything when something unexpected happened.
I think the Icon in the portrait gets overriden because i also apply a different mask texture.
Should be possible to make that compatible, will have to look at their code to figure out how to keep the spell icons when I apply my changes.
Thanks for the report, the pictures are very helpful!

**Comment by Karl-HeinzSchneider** [comment]
Can you try to comment out line 2914 and 2916 in 'Modules/Unitframe.lua'? 
````
function Module.RefreshPortrait()
    if UnitHasVehiclePlayerFrameUI('player') then
        -- SetPortraitTexture(PlayerPortrait, 'vehicle', true)
    else
        -- SetPortraitTexture(PlayerPortrait, 'player', true)
    end
end
````
Those two lines don't seem to really be neccessary, and in my quick test BigDebuffs works like expected, even when target switching. Only issue I found is that the playerframe sometimes refreshes and only show the number. But I guess the target frame is the important part.  Will investigate more next week when I have more time.

**Comment by Karl-HeinzSchneider** [comment]
I changed some more code, see #57 .
Seems to work like it should.

**Comment by dabadoo** [comment]
From just a very quick test it seems the issue described with PWS and switching target has been fixed.

The issue described here

> ![hibernate](https://private-user-images.githubusercontent.com/25304408/290777918-c310a276-4a9e-471a-8ded-fec841c77062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTk5MjMsIm5iZiI6MTcwNDYxOTYyMywicGF0aCI6Ii8yNTMwNDQwOC8yOTA3Nzc5MTgtYzMxMGEyNzYtNGE5ZS00NzFhLThkZWQtZmVjODQxYzc3MDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA5MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZGMxMjIwZWE2MTYzOGY1Nzg0MjNhM2EzYTM2MzIzODUyMDExYzNkZjZiYWYxMWM5ZjFmYmJmYTYxZWFlNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oXJu2zItrIgdewXNYWC4lKcUZrwhhjZLouMpJJDTfJk)
I tried disabling bidebuffs and enabled classucauradurations and the same thing happned. Text but no icon. I then tried disabling this addon and with classicauradurations only and it worked as expected ![Skærmbillede 2023-12-15 101034](https://private-user-images.githubusercontent.com/25304408/290778614-ebd56343-33c0-4cd7-94f2-1acded33c1be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTk5MjMsIm5iZiI6MTcwNDYxOTYyMywicGF0aCI6Ii8yNTMwNDQwOC8yOTA3Nzg2MTQtZWJkNTYzNDMtMzNjMC00Y2Q3LTk0ZjItMWFjZGVkMzNjMWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA5MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NWIxMTE0NTlmNzZmZDFjODI3ZGE2MjRmYzVjNzcyMWY5MDM3ZWVlZGU4YWI1ZDQwNzU4OWYyM2Q3YTM3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O_we23XZ5G-1mvt8_NR90lxh07qSYDUT09XHruuONA4)
> 
> Not getting any errors.

Still happens. I suppose it's not a bigdebuffs issue.

Seems good otherwise. 👍

**Comment by dabadoo** [comment]
Had this happen yesterday:
Had FF on me. Appears on my player frame and target frame as expected.
![picture 1](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/25304408/101db34e-51b4-4df5-a1d4-73c031d82a13)
But then without me changing targets or anything. Somewhere between 6 and 5 seconds left of the FF debuff my player frame only displays time left
![picture 2](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/25304408/9e9ce18f-4fe1-4532-810b-adc53b86e515)
