### ISSUE TITLE
Feature Request: Number of Actions for Bars 1-3

### ISSUE THREAD

**Issue by imreddy88** [Karl-HeinzSchneider/WoW-DragonflightUI#55]
Right now stuck with 1 row with 12 items for each of these action bars. Would like to limit to let's say only 8 items in the row.

**Comment by Karl-HeinzSchneider** [comment]
Next major version has that and more customization! 
Will be released in a few days.

**Comment by Karl-HeinzSchneider** [comment]
Update to v0.5.0 (online in ~1 hour!).  Let me know if you have any issues with the new update.
