### ISSUE TITLE
difficulty indicator stuck, 

### ISSUE THREAD

**Issue by Megumin230** [Karl-HeinzSchneider/WoW-DragonflightUI#65]
the difficulty indicator for normal and heroic is stuck where the vanilla blizzard minimap is, no matter the setting
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/70694639/b69028b1-9e88-456d-8f45-f661d99bb564)

**Comment by Karl-HeinzSchneider** [comment]
Hey,
you are right - thanks!
Fixed it for the next version. 
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/45100886-2537-408b-92b8-58037ae414f7)

**Comment by Karl-HeinzSchneider** [comment]
See commit 4236f43bf18cde90789e9929e844fff4dcb5976c
