### ISSUE TITLE
Request: Dark mode or FrameColor compatibility

### ISSUE THREAD

**Issue by sMuve** [Karl-HeinzSchneider/WoW-DragonflightUI#66]
Hi there,
awesome work! I really love the UI. I wanted to ask you, if you think it's possible to either introduce a dark mode or make it compatible with https://www.curseforge.com/wow/addons/framecolor-hud-action-bar-color ?

Best,
sMuve

**Comment by Karl-HeinzSchneider** [comment]
Hey,
not impossible to add, but a lot of work for not that many users. You're not the first one to suggest something like that.
Maybe someday, but not in the near future, sorry.
