### ISSUE TITLE
Incorrect placement of Difficulty Flag around minimap

### ISSUE THREAD

**Issue by Redledr** [Karl-HeinzSchneider/WoW-DragonflightUI#67]
I play on WotLK classic, the addon is v0.5.1, when entering any raid, the difficulty flag that displays the color and number of the participants is mal-positioned on the minimap. I really appreciate your take on the UI and I'm not asking for a style change, just an updated location! Thank you so much for what you do as a developer :)

v0.5.1 in BWL
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/37914092/83cc0e93-59a5-4195-9489-aa937bac1fb1)

Dragonflight
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/37914092/d510f8a8-3b89-4e62-b824-967a774a8ace)

**Comment by Karl-HeinzSchneider** [comment]
Hey,
already fixed for the next version, just didn't push it to curseforge yet.
See 4236f43bf18cde90789e9929e844fff4dcb5976c .
You can change the code yourself and try it out, or wait for the next update.
