### ISSUE TITLE
Cyrillic font is missing

### ISSUE THREAD

**Issue by RustamTastimullin** [Karl-HeinzSchneider/WoW-DragonflightUI#72]
Cyrillic font is missing.
There should be "K".
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/54327939/331a0fa7-998b-4f9b-86d6-21837be38e72)

**Comment by Karl-HeinzSchneider** [comment]
Hey,
please test something for me:

go to "UnitFrame.lua" line 2810, and insert the following code:
``` 
 if GetLocale() == "ruRU" then newFont = "Fonts\\FRIZQT___CYR.TTF" end
```


so it will look like that:

``` 
function Module.ChangeFonts()
    local newFont = 'Fonts\\FRIZQT__.ttf'

    if GetLocale() == "ruRU" then newFont = "Fonts\\FRIZQT___CYR.TTF" end
    
    local changeFont = function(f, newsize)
        local path, size, flags = f:GetFont()
        f:SetFont(newFont, newsize, flags)
    end

    local std = 11

    changeFont(PlayerFrameHealthBarText, std)
... ... ...

end
```
Maybe this will fix it. The "K" etc comes from a blizzard function to breakup large numbers; if this doesn't work, I would need to dig deeper.

**Comment by RustamTastimullin** [comment]
Yes! This line fixes up the problem!
Thank you for the fix!
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/54327939/de295177-4be6-4c79-8155-8fd6642679e3)

**Comment by Karl-HeinzSchneider** [comment]
Nice, and thanks for reporting!
Will be in the next version as fix.
