### ISSUE TITLE
Action bars are not hiding properly

### ISSUE THREAD

**Issue by abgonzalez93** [Karl-HeinzSchneider/WoW-DragonflightUI#73]
**Actions bars are not getting hidden** even though in Wow interface and the addon configuration, the **Always show action bar** check is **unchecked**

_They hide once you press P and skill book opens..._
_They also disappear if you mouseover it_

![imagen](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/39385878/f28f5325-4081-4945-a48c-ae09c4ba5b53)

![imagen](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/39385878/f8ede449-dadf-4124-892e-3ce1aa51effe)

**Comment by Megumin230** [comment]
they also dissapear again if you hover the mouse cursor over the slots, but they reappear anytime

**Comment by Karl-HeinzSchneider** [comment]
Please check "Always Show Action Bars" in the Blizzard Options, and let Dragonflight UI manage show/hiding. Set your prefered options, and "/reload" once to make everything work correctly.

**Comment by abgonzalez93** [comment]
That worked 👌🏻
