### ISSUE TITLE
Feature Request: Profiles

### ISSUE THREAD

**Issue by jvdnbus** [Karl-HeinzSchneider/WoW-DragonflightUI#74]
Great addon so far, I see you have Profiles in mind but they are not working as of yet. I'd really like to see this implemented as on some characters I prefer using Dominos for my action bars and currently modules are either enabled or disabled for all of them.

For now I've simply made a dirty edit to enable modules['Actionbars'] on one of my characters specifically.

Thanks!

**Comment by Karl-HeinzSchneider** [comment]
Hey,
profiles will be implemented (again) for the next version.
Should be out in 3-5 days.

**Comment by Karl-HeinzSchneider** [comment]
Feature completed for v0.7
