### ISSUE TITLE
Anchoring issues with default UI objects around minimap

### ISSUE THREAD

**Issue by Aetherdan** [Karl-HeinzSchneider/WoW-DragonflightUI#77]
I've noticed that there is anchoring issues with things like the durability doll and the boss frames, especially when you have the quest tracker open. See screenshot for reference. 

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/29881062/433106e3-c4e7-4d4e-99b2-5b15c7a18fa2)

Absolutely love the work done with this, its a much cleaner gaming experience already <3

**Comment by Megumin230** [comment]
increasing the minimap size also messes with the quest tracker, a bigger minimap blocks the text for the top quests, so maybe a option to move quest tracker?

**Comment by Karl-HeinzSchneider** [comment]
New Customization for the DurabilityFrame and Questtracker:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/e4392d4c-250d-4baf-86e2-17dd2b2a8dc6)
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/591c9d17-1b9f-4e0c-92ac-be3dd7d03c7b)
Available in v0.7 (soon! 😎)
