### ISSUE TITLE
Feature Request: Split Modules More

### ISSUE THREAD

**Issue by riparoo** [Karl-HeinzSchneider/WoW-DragonflightUI#78]
I love this addon for Cataclysm but I am sadly not really able to use it fully while using Bartender4. I like the Micro Menu and the Exp/Rep bars much more from your addon but when you enable the Actionbar module while also using Bartender4 you cant move or scale the exp/rep bars even if you disable them Bartender4. The Micro Menu is still sort of usable but cant really move it. I know this is a compatibility issue but I was hoping if you could at least split the modules up a little more finely then we could still use this addon alongside Bartender4

**Comment by Karl-HeinzSchneider** [comment]
Compatibility with Bartender is definitly out of scope.
What are you using Bartender for, or in other words, what would you need as features etc?

**Comment by riparoo** [comment]
> Owner
Really was just looking to be able to enable the micro menu and the rep/exp bars without having to enable all actionbar control.

**Comment by Karl-HeinzSchneider** [comment]
Won't be implemented in the near future.
Please open a new feature request if you have ideas to improve the action bars, so you could ditch Bartender.
