### ISSUE TITLE
Pet Frame Keeps Resetting Positioning

### ISSUE THREAD

**Issue by kurcenkurce** [Karl-HeinzSchneider/WoW-DragonflightUI#80]
When changing Dragonflight UI -> Unitframes -> Pet -> Anchorframe to Playerframe and then setting the appropriate X-Y coordinates, the positioning of the frame is not remembered after reloading. It appears it keeps resetting back to a default positioning. As soon as you modify the X-Y coordinate by even one pixel, the frame will "jump" to the appropriate position on the screen.

From what I can tell, it doesn't look like it loads the saved values and reverts to a default when the addon is first loaded. As soon as a value is changed, then the modifications are applied.

**Comment by Karl-HeinzSchneider** [comment]
The Petframe is always wierd, because the Blizzard code is all over the place, but I'll take a look. 
I dont really play a class with pet, so I don't encounter most issues.
The Cataclysm update changed something about the pet stuff, but right now I just fixed the errors that kept popping up.

**Comment by Karl-HeinzSchneider** [comment]
Fixed for the next version: f7d9869ec6547d98f58fd0ade08fb042a4110282
