### ISSUE TITLE
Pet Health/Mana Text Format Inconsistent with Player Frame Health/Mana Text Format

### ISSUE THREAD

**Issue by kurcenkurce** [Karl-HeinzSchneider/WoW-DragonflightUI#81]
Player health is of the format "%         Current Health (Short)"
Pet health is of the format "(%) Current Health (Long) / Max Health (Long)"

Would it be possible to make these match?

**Comment by Karl-HeinzSchneider** [comment]
It's possible, but would be a low priority. 
At the moment the UI uses the default HP/Energybar displaytext logic for maximum compatibility with other Addons/WA's etc.

**Comment by Karl-HeinzSchneider** [comment]
I agree that it looks wierd:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/0e214711-203f-4318-8315-ffe1e3160a77)
Maybe I'll improve it later in a small update.

**Comment by kurcenkurce** [comment]
Yeah, I disabled Dragonflight UI and looked at the basic Blizzard frames and they do the same thing. So weird that it looks like that. If there is an addon/workaround, I would be interested to know. I understand if you want to keep this as minimal as possible for compatibility reasons.

**Comment by Karl-HeinzSchneider** [comment]
I guess one problem is, that the Pet Health/Manabars are so small, the percent + absolute values wont fit the same way. 
How would you style it? Are Pet values even relevant anymore? Maybe they could just be hidden to not look strange.

**Comment by kurcenkurce** [comment]
I personally would like that. Seeing their actual health or their percentage is not actually relevant.

**Comment by Karl-HeinzSchneider** [comment]
Option to hide the text: 4bc968871e08d2d25c1b4afe41141a0fae59c4c4
You can test it now, but the update for the new version will go out in 2-3 days maybe.

**Comment by kurcenkurce** [comment]
Looks great to me! Very nice and clean.
