### ISSUE TITLE
Focus ToT dead text/texture

### ISSUE THREAD

**Issue by Blakewow** [Karl-HeinzSchneider/WoW-DragonflightUI#85]
Hi there, any futur fix for the dead text/texture on the target of target from focus unitframe ?

![totdeadtexture](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/171361365/c8444533-1907-4af0-b9ba-f3a612da93b4)

**Comment by Karl-HeinzSchneider** [comment]
Thanks for reporting!
Fixed for the next version, see c44eabb4a4dd6c4e891873cb8ef2715ace662d7c

**Comment by Blakewow** [comment]
ty !

**Comment by Karl-HeinzSchneider** [comment]
Relevant fixes: ee442ee84faf99768d9a78082cdde0e972e2a709
UnconsciousText, and focusToT background texture as seen in your screenshot.
