### ISSUE TITLE
Make padding/scale sliders smaller increments?

### ISSUE THREAD

**Issue by JayMoorhouse** [Karl-HeinzSchneider/WoW-DragonflightUI#93]
Firstly you're a god. thank you for this. This is a very minor request--sorry if it's a bit too particular...

Anyway, on DF the padding is whole numbers and the scale is 10% increments:

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/31828875/9751865c-b062-4b99-b318-ca51fba14bcb)

However with these values, it's possible to lineup a larger scale action bar start/end to smaller ones with matching padding (i.e. top row is larger but it still lines up):

![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/31828875/abc34584-edba-49bd-b4c2-d101584edcd3)

On DFUI classic, these values don't have the same result (expected, I understand), but is it possible to make padding/scale smaller increments in order to more closely control them? E.g. scale @ 1% increment and padding to the .1?

Scale 1.20, padding 1
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/31828875/935a8261-bd93-49a3-ab5f-75ec5c8ace74)

Sale 1.20, padding 2
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/31828875/fcf6ab3e-8806-44e9-bde1-ef1792083ecd)

With padding/scale values, it's impossible to line up the start/end of the top actionbar to the others like in first screenshot. E.g. padding 1.5 would do this.

<3<3

**Comment by Karl-HeinzSchneider** [comment]
Hey,
If i dont find any issue with it, I will include it in the next version.
You could test yourself if its how you would like it:

go to: Modules/Actionbar.lua ,line 465-473
```
 padding = {
    type = 'range',
    name = 'Padding',
    desc = '' .. getDefaultStr('padding', barname),
    min = 0,
    max = 10,
    bigStep = 0.1,
    order = 11
},
```
You can play with the value "bigStep", e.g change '1' to '0.1'

You could also change line 438-446

```
 buttonScale = {     
    ...
    bigStep = 0.1,
    ...
},
```
and use '0.05'

There might be rounding errors with too small values tough.


After wildly clicking around for two seconds I got this:
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56960197/315fb1e2-81da-4590-b595-30b132f8b174)
Seems close.

**Comment by JayMoorhouse** [comment]
works like a charm. I made padding 1.5 and it's perfect :) thanks so much again for both the addon and now for your help
