### ISSUE TITLE
Pet's Health/Mana Always Shows Even if Disabled

### ISSUE THREAD

**Issue by kurcenkurce** [Karl-HeinzSchneider/WoW-DragonflightUI#95]
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/17913700/f315b67c-0a02-4a98-92be-232b697ba56f)
![image](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/17913700/a7ce26f7-a3db-40d3-998f-8c2a57e252d1)

I presume the fix for the health/mana not showing on the main player frame has made it where the pet's health/mana *always* shows up regardless if the checkbox is turned off.

**Comment by Karl-HeinzSchneider** [comment]
I'll fix it for the next version (2-3 days)

**Comment by Karl-HeinzSchneider** [comment]
Blizzard fixed their Interface Code, and also added the Health/Manabar Left/Right fontstrings

I fixed it for the next version. See 00e84b65da224441d9ce9dea3e198312c113de20 if you want it now.
