### ISSUE TITLE
A bug in wotlk3.4.3,need help plz.

### ISSUE THREAD

**Issue by BennLiu** [Karl-HeinzSchneider/WoW-DragonflightUI#98]
![1718531458131](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/102046809/86ddea1c-5a24-452d-a1bb-f47d83e9dcd6)
As you can see, the spell icon has repeatedly appeared in the lower left corner of the game interface.
 It will disappear only when the spell icon is removed from the actionbar. 
 thank you!
Game version:wotlk 3.4.3

**Comment by Karl-HeinzSchneider** [comment]
I'm not supporting private server.

**Comment by BennLiu** [comment]
> I'm not supporting private server.

Actually, this is an official Blizzard server, and the game is set to return this month.
<img width="591" alt="image" src="https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/102046809/d1233aa6-2239-42b7-8a73-1224413fbc0e">

**Comment by Karl-HeinzSchneider** [comment]
But 3.4.3 is a different Client, and I cant play on chinese servers to test/debug.
