### ISSUE TITLE
Some Feedback on the addon

### ISSUE THREAD

**Issue by Cortes-Jeremy** [Karl-HeinzSchneider/WoW-DragonflightUI#99]
Hi, 

I dont know where to put thoses feedbacks, so I opened this issue.

First I want to thank you for this addon, I really appreciate playing with it.
My version is Cataclysm Classic and I have joined some screenshots so illustrate thoses points: 

1)  TargetFrame TargetOfTarget and FocusFrame TargetOfTarget are not Class colored. (Clipboard01)
2)  Stance Bar dont have the new "actionbar" border texture (Clipboard02 - 03)
3)  Missing a small button next to player Buffs to hide/show them (like bags have) (Clipboard04)
4)  Reputation bar and experience bar are ignoring scaling put in config (and they seems way bigger than retail) (Clipboard05 - 06)
5)  Minimap button border for Battlegound and Addons are old texture (Clipboard07)
6)   I read somewhere that you dont want to do the target / focus castbar, can you tell what is the problem to them ?

![Clipboard01](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56119078/deaf72f0-e777-42df-86b6-97bc611243bd)
![Clipboard02](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56119078/119871d1-8886-4077-940d-abe1508c4f74)
![Clipboard03](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56119078/1520f8cd-d570-41fc-bd29-fb35ca5ae332)
![Clipboard04](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56119078/2378839b-c432-4626-b7ee-d39f622c0045)
![Clipboard05](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56119078/de99c7f6-5587-462b-9565-a32fd3b84039)
![Clipboard06](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56119078/3e527e57-96da-4a63-89fd-be56ff48a257)
![Clipboard07](https://github.com/Karl-HeinzSchneider/WoW-DragonflightUI/assets/56119078/7ac499b5-5538-4ac0-843c-e266c629e0bf)

**Comment by Karl-HeinzSchneider** [comment]
Hey,
Issue is fine!

1) Quick implementation: d8b631d4b2d948c8b16841495e190ed0d97af874
2) StanceBarButtons are bit different than normal Actionbuttons, thats why I only did some changes, but I'll take a look at them again.
3) I don't think many would use this, but should be a small code change.
4) They need a rework (again), but I'm not aiming at 1:1 Dragonflight remake.
5) Battleground Icon could get a touchup yeah, I recently changed the LFG to the Dragonflight one. But Addon minimap buttons might be out of reach for a quick fix.
6) I want to do them, but they are quite a bit of work.

**Comment by Karl-HeinzSchneider** [comment]
2.) #146, same with PetBar in #149

**Comment by Karl-HeinzSchneider** [comment]
3.) 54ce9f64d2f7c2efb908e4ab0ce9bfba9025f1fb

**Comment by Karl-HeinzSchneider** [comment]
All done!

**Comment by Cortes-Jeremy** [comment]
Look Good ! Thank you very much.
